### ISSUE TITLE
[Hunter]Arcane Shot working normally, please close 

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#100]
Arcane Shot seems to be working.
Please Close.

**Comment by Ifixstuffk** [comment]
http://wowwiki.wikia.com/wiki/Arcane_Shot
Reference patch notes

**Comment by Yiemeh** [comment]
Nice try

**Comment by Ifixstuffk** [comment]
Pardon? It is. It had 20% right up to BC where it was reduced.
That being said, I do believe it is scaling now.. I have increased my AP and have seen a small difference.
