### ISSUE TITLE
[Warlock] Talent Improved Imp does not increase blood pact accordingly

### ISSUE THREAD

**Issue by Seoulboy1** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#1104]
Improved Imp talent in the Demonology tree is bugged atm. Fire Shield seems fine along with fire bolt, but Blood pact does not improved properly. The tooltip does correctly show the modified number, but the actually buff itself does not increase.

**Comment by devidao** [comment]
Tested on PTR, working fine now.

**Comment by Nzzoth** [comment]
The aura needs to be reapplied in order for the effect to take place. Tested on PTR and it's working as intended. Issue closed.
