### ISSUE TITLE
[General] Keys and Doors - Pick Lock - Lockpicking

### ISSUE THREAD

**Issue by mike142** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#1144]
If you Right Click on a key and Left Click on a Door which is supposed to be opened by that key you will notice that you're able to open the Door from any distance.

**Comment by devidao** [comment]
Fixed. maximum possible distance now is 5 yards.

**Comment by Kaiitothewai** [comment]
This was applied with Patch 11.7
http://www.wow-one.com/forum/topic/95872-project-phoenix-1121-changelog-patch-11/?p=730803
