### ISSUE TITLE
[Hunter][Creature][Pet] Razzashi Serpents and Adders

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#118]
These snakes in Zul'Gurub do not have Poison Spit, and their Diets are incorrect. 
Snakes diets are supposed to be Meat (NOT Fish / Cheese / Bread)

and they are supposed to carry Poison Spit Rank 3 as a Tameable Ability.

http://wowwiki.wikia.com/wiki/Razzashi_Serpent
http://wow.gamepedia.com/Razzashi_Adder
http://db.vanillagaming.org/?npc=11372#abilities
http://wowwiki.wikia.com/wiki/Razzashi_Adder

**Comment by Ifixstuffk** [comment]
http://www.tentonhammer.com/guides/wow-hunter-guide-pet-skill-list-page-2-e48803dc-2b72-4d22-95a5-7e4d77a30860#poisonspit

Poison spit is a ranged attack that once it hits causes nature damage to the target over 8 seconds. It is a very nice DOT effect and one that many hunters wish they had available on a pet other than serpents.

Range: 30 yards 
Cost: 35 Focus
Cooldown: 10 seconds
Available to: Serpents

Rank 3
Damage (over 8 sec.) 120
Level Required 60
Training Point Cost 25

**Comment by Ifixstuffk** [comment]
#120

**Comment by devidao** [comment]
- Added Razzashi Serpents and Adders tamed spells 
- Made that they can eat meat only
