### ISSUE TITLE
AV level bracket issue

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#12]
When queing up for Alterac valley it puts you in 0-10 level bracket as a level 60 character.

Desired: It should correctly put you in level 60 bracket.

Reproduction:
.gm off
.gm visible on
.go c Thelman_slatefist

**Comment by ivid** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by anaaz** [comment]
Fix applied on live with Patch 12.1
