### ISSUE TITLE
[Hunter] Viper Sting breaking Freezing Trap

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#126]
Viper Sting deals no damage, and is not supposed to break freezing trap.
Tested in 5 duels outside of Durotar.

Quote from the Freezing Trap tooltip: "Any damaged caused will break the ice."

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by sycvil** [comment]
[wowwiki, November 2006](http://wowwiki.wikia.com/wiki/Freezing_Trap?oldid=347848):

> Any damage caused will break the ice (this includes DoTs such as Serpent Sting and Viper Sting). 

[archived thottbot, September 2006](http://web.archive.org/web/20060918143926/http://www.thottbot.com/?sp=14280):

> viper sting takes off the freezing trap btw, ya i know it sux 
> 
> The drain counts as damage. Just... try it. 

[Some German site, May 2005](http://wow.gamona.de/forum/threads/eigentl-m%C3%BCsste-dass-doch-gehen.55215/) ([Google translate version](https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=http%3A%2F%2Fwow.gamona.de%2Fforum%2Fthreads%2Feigentl-m%25C3%25BCsste-dass-doch-gehen.55215%2F&edit-text=)). I don't know German but from what I understand a GM was asked why using Viper Sting without breaking Freezing Trap does not work and the answer was that this behaviour is intended. Some comments in that topic seem to confirm that it does not work and would be too OP.

From [http://wowwiki.wikia.com/wiki/Talk:Freezing_Trap](http://wowwiki.wikia.com/wiki/Talk:Freezing_Trap):

> A long time ago it didn't use to break Freezing Trap because it wasn't a damage effect, but it has been stealth changed now so that it does in fact break FT. Any sting except Scorpid Sting will. --- Zexx 06:15, 14 September 2007 (UTC) 

Info when approximately it was "stealth changed" can be found on [another German site](http://forum.giga.de/mmogs/393202-j%E4ger-vs-magier-3.html#post5069994) ([Google translate version](https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=http%3A%2F%2Fforum.giga.de%2Fmmogs%2F393202-j%25E4ger-vs-magier-3.html%23post5069994&edit-text=)) (post 39). If I understand correctly it is stated that Viper Sting did not break Freezing trap prior to patch 1.5.

**Comment by dagochen** [comment]
Viper Sting should break the trap :)

**Comment by Yiemeh** [comment]
Yes, same as it should also break Sheep and other CC effects that breaks on damage.

**Comment by Ifixstuffk** [comment]
Its not a damaging effect. Posting comments without proof.. Ill look through some hunter videos to confirm. 
I know it broke in Arena during TBC (this is why evvery hunter uses scorpid in arena), but shouldnt have prior.

**Comment by dagochen** [comment]
http://wow.gamepedia.com/index.php?title=Freezing_Trap&oldid=178850

**Comment by Ifixstuffk** [comment]
Does a warlocks mana drain break any CC? Can someone confirm please?

**Comment by Forcy** [comment]
Fix confimed

**Comment by xiaoxoxo** [comment]
are u serious?

**Comment by furosexitus** [comment]
> Info when approximately it was "stealth changed" can be found on another German site (Google translate version) (post 39). If I understand correctly it is stated that Viper Sting did not break Freezing trap prior to patch 1.5.

Native german here; you understood correctly. The original poster clearly states in "vor 1.5 war sogar im Duell ein gut gespielter Hunter zu 75% der winner,als der Viperbiss die Eisfalle noch nicht untertbrochen hat..." that viper sting didn't interrupt the freezing trap prior 1.5. Literally translated, 'before 1.5, a well played hunter won 75% of the duels when viper sting didn't interrupt the freezing trap'.

**Comment by Zerixx** [comment]
If this doesn't work come launch (blizzlike, I mean) I'll revert this.

**Comment by Asinin3** [comment]
This is going to kill pvp for casters, I actually mained a hunter in retail vanilla and can recall viper breaking trap late patch. I know it's not proof but how about looking at other vanilla servers how is this handled on Elysium for instance?

**Comment by Zerixx** [comment]
Find proof. If there is none, then I guess Elysium will do.

**Comment by Oceangraves** [comment]
https://youtu.be/XgFHoXedgSc?t=3m55s I don't want to sound rude but it took me only a couple minutes to find that

**Comment by Asinin3** [comment]
https://youtu.be/uUgCR7k6PvI?t=14m52s That good enough?

**Comment by Zerixx** [comment]
That's exactly what I needed to see.

**Comment by teddys** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1989

**Comment by Asinin3** [comment]
If anyone wants proof of it breaking scatter shot: https://youtu.be/uUgCR7k6PvI?t=9m47s also **viper only breaks cc on ticks**. You can apply viper to cc and it won't break until the first tick of viper sting. Proof: https://youtu.be/GEcRDP304kU?t=15m30s This means hunters are able to viper then open with multi-shot before cc breaks saving a gcd.

**Comment by Zerixx** [comment]
Fixed. Reverted and will find its way to live soon.
