### ISSUE TITLE
[Hunter][Spell] Aimed Shot casting pushback

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#127]
Aimed Shot is a Shot, not a Spell subjected to pushback. It is only using your Ranged weapon and Ammunition.
 It does not even have a cast bar, I suspect for this reason.

I can find absolutely no mention of any pushback to any shot outside of Steady Shot in The Burning Crusade.

**Comment by Flexiii** [comment]
It always had pushback.

**Comment by devidao** [comment]
so is it a bug or no?

**Comment by Flexiii** [comment]
It is not a bug, working as intended. Took me 1 minute to research.
Aimed shot pushed back by Vaelstrasz AoE ticks:
Dated Dec 3, 2006
https://www.youtube.com/watch?v=YJkKedeyWnE

**Comment by Asinin3** [comment]
This definitely is not bugged, this isn't the first time you have posted a report for something that isn't actually bugged either. Please find proof before making a report, we don't need people wasting time fixing something that isn't bugged in the first place.
