### ISSUE TITLE
Argent Dawn / Cenarion Circle Epics

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#128]
These were non-existent in the "current content patch" available.

**Comment by devidao** [comment]
need more specific about this issue

**Comment by Ifixstuffk** [comment]
Will provide in a few hours

**Comment by Ifixstuffk** [comment]
http://www.wowhead.com/quest=8573/champions-battlegear
http://www.wowhead.com/quest=8574/stalwarts-battlegear

Cenarion Battlegear items were added in 1.11 with the release of Naxxramas

http://www.wowhead.com/item-set=513/feralheart-raiment#comments

If you check the comments, dungeon set 2 was not made available until Patch 1.12

Argent Dawn 
http://www.wowhead.com/quest=9222/epic-armaments-of-battle-friend-of-the-dawn

Added 1.11 with the release of naxxramas

**Comment by Nzzoth** [comment]
Hello,

I do understand how this in fact is an issue. However this is a feature, we do not wish to limit players nor completely recreate the path retail took.

Prior to release this was discussed and agreed to be left in the game.

Issue closed and denied.
