### ISSUE TITLE
Songflower and other Felwood buffs

### ISSUE THREAD

**Issue by Bierflasche** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#134]
When turning in [Salve](http://www.wow-one.com/database/index.php?item=11516) at [Corrupted Songflowers](http://www.wow-one.com/database/index.php?quest=2523) one does not receive the [Songflower buff](http://www.wow-one.com/database/index.php?spell=15366). I didn't test the other flowers (neither know the buff name), dunno if it is the same there.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
