### ISSUE TITLE
[Warrior][Spell] Slam only works from the Front

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#138]
Slam is currently acting like Gouge, only letting you use it in a frontal cone.
It should be usable from any direction.
This is a VERY crippling bug for Warriors and has been around for a long time.

https://www.wow-one.com/database/index.php?spell=11605

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
