### ISSUE TITLE
Dueling Players can be dispelled by those not involved

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#142]
Pretty much the title.. Nobody should be able to interact with any duelers

**Comment by gianclaudio-giordano** [comment]
Also if one of the players dueling i grouped with a shaman, the totems auras will also affect him/her  during the duel.

**Comment by lajhar** [comment]
Patch Note **1.6.0**:
Dispel Magic can no longer be used on players participating in a duel unless the caster is in the duel.
