### ISSUE TITLE
Channeled spells do not break on Out of Range 

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#143]
Pretty much the title, easy to recreate. Duel someone, cast a channeling spell such as Arcane Missiles, run out of range. It won't stop.

**Comment by gianclaudio-giordano** [comment]
This is blizzlike.

**Comment by Ifixstuffk** [comment]
Fixed\*

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
