### ISSUE TITLE
[Item]Wrath of Cenarius

### ISSUE THREAD

**Issue by Vittnet** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#146]
https://www.youtube.com/watch?v=9vVG1-TmYA8&feature=youtu.be

Equip: Gives a chance when your **harmful** spells land to increase the damage of your spells and effects by 132 for 10 sec.

The item should only proc on harmful spells but it can proc of any spell.

https://www.wow-one.com/database/index.php?item=21190

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
