### ISSUE TITLE
[Druid] Weapon Damage is incorrectly applying to cat form

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#147]
It should not apply at all, nothing weapon damage related worked in cat form (hence why it was not used, a Cat has paws, not weapons)

**Comment by Yiemeh** [comment]
Correct, but there is one exception, the +4 damage ring should work. 
http://www.wowhead.com/item=21189/might-of-cenarius
http://thedruidsgrove.org/archive/wow/t-12335.html

There is some arguing back and forth in these links but if you read through it the conclusion is the ring works, enchants and weight stones don't.

**Comment by Ifixstuffk** [comment]
There is no conclusive detailed answer or proof that the ring works, just people arguing that it should or should not.

**Comment by devidao** [comment]
Fixed.
- Player in cat/bear form cant apply any weapon damage increasing aura (except item ID: 21189, Might Of Cenarius ).
- If player enters in cat/bear form when he has weapon damage increasing auras then that auras are disabled and when he back to normal form or change to other form then that auras are enabled again.
