### ISSUE TITLE
[Silithus] Twilight Trappings used on any tier of Wind Stones will consume multiple sets

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#152]
Collect multiple twilight trappings sets, equip 1
Click a stone to summon a Templar
Check inventory, you will notice 2 (or all) sets have been consumed.

**Comment by devidao** [comment]
I have just tested, but consumed only one set. I made test in this way:

1) .additemset 492
2) .additemset 492
3) .additemset 492
4) equip one of the sets
5) .go object "Wind Stone"
6) Click on the "Wind Stone" and select gossip option.

**Comment by ivid** [comment]
There is already a fix for it on PTR: https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/40

**Comment by devidao** [comment]
right, it means fix still is not applied on the Live
