### ISSUE TITLE
@issue #135

### ISSUE THREAD

**Issue by Flexiii** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#159]
Just wanted to bump it before it goes on PTR and possibly live since Devidao posted that he "fixed" it.

The mechanics described in issue #135 is not a bug and works exactly the same as in vanilla 1.12 and was never changed at least for whole vanilla period.

Video dated 30 April 2006:
https://www.youtube.com/watch?v=Q0O4RKeD4g4

There is more evidence that it worked same way as on Feenix now, mostly on old forums from frustrated rouges and druids.

Perhaps people posting potential bug report and devs before putting any work into fix should do some research.
Looks like devs take players opinions on game mechanics too easy.
In general there are many bug reports here that look like: "I don't like it therefore it's a bug".

**Comment by xiaoxoxo** [comment]
Totally agree with flexiii, this is a blizzlike feature. Don't try to "fix" stuff unless there are sources.

**Comment by Zerixx** [comment]
Alright
