### ISSUE TITLE
Guild client crashes

### ISSUE THREAD

**Issue by Field-** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#1688]
When a guild has ~730+ members, certain actions will cause client crashes for every player inside that guild.

**Comment by Aurigon** [comment]
What does that imply exactly... is it fixed, still being tested, will be back on live anytime soon or?

**Comment by ender-feenix** [comment]
Yes I believe you are right as to the reason for there not being a specific limit.  What my previous message meant was just that the limit has been live for a while, but the database change that was missing was the exact string of the error message you would receive if your guild became too full.  So, before the database update was applied you would receive an "Unknown error" sort of message.  Now you will receive a "Guild is too full" sort of message.  This fix went live with 10.3 and I just forgot to close the issue.  So, closed now!
