### ISSUE TITLE
Hearthstone issue

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#17]
Hearthstone (ID: 6948) doesn't go on cooldown when used.
Noteworthy mention, check aswell after you use it when and if it goes on cooldown when you relog if it's still on cooldown.

Desired: It goes on a 60 min cooldown.

**Comment by ivid** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by anaaz** [comment]
Fix applied on Live 23/06/2016 Patch 12
