### ISSUE TITLE
[Druid] Feline Swiftness Talent

### ISSUE THREAD

**Issue by Celaris** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#1859]
Feline Swiftness doesn't activate when you switch from an indoor to an outdoor area, for example if you leave a building. Instead it forces you to leave cat form and use it again to reactivate the speed bonus.

Weirdly it does work the other way: If you enter a building the movement speed bonus is deactivated automatically.

**Comment by Kaiitothewai** [comment]
**Fix is ReConfirmed on PLTR**

**Comment by Kaiitothewai** [comment]
#5012

**Comment by Kaiitothewai** [comment]
Live.
