### ISSUE TITLE
[Instances] Limitations on entering/resets

### ISSUE THREAD

**Issue by lucridus** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#1886]
As of Patch 1.9 or so, players are limited to entering 5 instances per hour. Meaning that if you start your first run at 1:00pm, and do 4 more runs within an hour, you will not be able to enter any more instances (aside from Battlegrounds) until it is 2:00pm.

* Example

  * 1:00 : Instance 1 entered
  * 1:10 : Instance 2 entered
  * 1:20 : Instance 3 entered
  * 1:30 : Instance 4 entered
  * 1:40 : Instance 5 entered
  * 1:50 : Instance 6 Unable to enter. You will simply walk through the portal without entering the instance.
  * 2:00 : Instance 6 entered

It should return an error message similar to, "You have entered too many instances recently. Try again later".
This isn't exact but there should notify you of the problem in yellow text. The same applies to raid instances.

Note: The number of instances you can enter is linked to your other characters on the same account as well. This means that if you have reached the entering limit on character A, character B will not be able to enter any instance.

http://www.wowwiki.com/Instance_limitations

**Comment by Goanno** [comment]
Fix confirmed on PTR
- If you try to walk in a 6th instance within an hour you walk into a 'wall'.
- Exactly an hour after you entered an instance, the instance save for that instance ID goes away.

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
