### ISSUE TITLE
[QUEST][Stormwind] The Binding

### ISSUE THREAD

**Issue by vulcan1701** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2]
This is for the new Warsong server.
There is no Stormwind Summoning Circle in the crypt to complete this quest.
Attempts in all crypt locations result in "Requires Stormwind Summoning Circle" message

**Comment by anaaz** [comment]
Hello,

I have to reject this report as this quest is working on Warsong. 

regards,
Anaaz
