### ISSUE TITLE
[QUEST][Taming the Beast] Razor Hill HUNTER Surf Crawler

### ISSUE THREAD

**Issue by Vimpil** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#20]
Overview of quest:

The second pet taming quest in the chain of three for hunters in the Orc and Troll starting area of Durotar. It has the hunter capture a Surf Crawler for use as a pet. http://wowwiki.wikia.com/wiki/Quest:Taming_the_Beast_(Orc_and_Troll_2)
*

Problem:
If the player will use not the Taming Rod (http://wowwiki.wikia.com/wiki/Taming_Rod) from inventory (), but the spell with the same icon from spellbook (Taming), quest willn't be done.

**Comment by devastator** [comment]
I guess this is intended. Comments on wowhead on the topic:

By omtard (109 – 2)  on 2008/02/10 (Patch 2.3.3)   

what do you do if your taming rod runs out of charges?

Bloodlusted on 2008/04/09  (Patch 2.4.1)
Destroy the rod, abandon the quest, and then get the quest again. 

Closing until further evidences are found supporting that using the spell from spellbook also works for completing the quest
