### ISSUE TITLE
[QUEST] The Pariah's Instructions BUGGED

### ISSUE THREAD

**Issue by cromruswar** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#21]
Greatings! Yesterday i wrote to you a ticket about a quest "The Pariarh's Instructions" in Desolace. About the bugg of this quest. Spirit of Magra, the Third Khan, walking on nearly textures, and when you try to use quest item (Amulet of Spirits), the system write a message "Target not in line of sight".  Help me please. Fix the bugg of quest, of just give me the Gem of the Third Khan, for comlete it.

Phoenix 1.12.1, Warsong, Cromrus, warrior, 60th lvl, tauren

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/11
