### ISSUE TITLE
[ITEM] Biznicks 247x128 Accurascope

### ISSUE THREAD

**Issue by Kaiitothewai** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2190]
**Current Situation**
* Gives 3% hit to Melee and Ranged.

**Desired Situation**
* Gives 3% hit to Ranged.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
