### ISSUE TITLE
Rare spawn Deathmaw cannot be tamed

### ISSUE THREAD

**Issue by scarabadookie** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#22]
The rare spawn wolf Deathmaw ( [www.wow-one.com/database/?npc=10077](url) ) in Burning Steppes gives "creature cannot be tamed message" on attempting to tame it, should be tameable by hunters. She's one of the better pets in the game due to an attack speed of 1.20, so it would be great if she could be tameable. 

Thanks!

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by anaaz** [comment]
Fix applied on live with Patch 12.1
