### ISSUE TITLE
[Quest/Objects] Wrong Interaction or Tooltip hover issues

### ISSUE THREAD

**Issue by lucridus** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2303]
__Issue:__ There are objects in the world such as Corpse Laden Boat (ID:1593) and all Wanted Poster objects that shouldn't be interact-able or yield a tooltip unless they offer a quest or are part of a quest. You should not be able to interact with objects or even target them unless they are part of a quest.

__Desired result:__ The Wanted Posters should only interact if you are able to log a quest. Once you've logged a quest, the Wanted Poster should not interact or even yield a tooltip upon hover. If you drop the quest the Wanted Poster should allow interaction to re-log the quest. If you've completed the quest it should not even be possible to hover over the object with your cursor. 

* Some examples:
  * The Corpse Laden Boat (ID:1593) should only be interact-able or hover-able with your cursor if you are on that exact quest (ID:438) that involves the boat.
  * The Well inside Tarren Mill also yields an incorrect hover tooltip with "TEMP Spring Well".
  * UBRS door with the flame doodads being hover-able and even interact-able by right-clicking.
  * The Argent Hold (ID:176317) object should only interact if on quest (ID:5265). If not on quest, you should not be able to interact or hover over the object yielding a tooltip.

If correctly fixed, this should fix a lot of the random gossip problems when right-clicking objects that yield incorrect gossip text such as "Greetings NAME".

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by ender-feenix** [comment]
Note that this now needs testing on the PLTR

**Comment by Salce** [comment]
**This went live with Patch 11.0**
