### ISSUE TITLE
[PRIEST] [SPELLS] [TALENT] Shadowguard / Touch of Weakness is not proccing blackout.

### ISSUE THREAD

**Issue by Hulg** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2337]
Apparently, troll priest racial skill Shadowguard is not proccing blackout at all. This happens with all the ranks of Shadowguard.

**Comment by Nothhelm** [comment]
"For Shadow Priests this spell is extremely powerful. In addition to its good damage, it has three chances to proc Blackout, Shadow Weaving, and "passive" Vampiric Embrace healing." 
From 2006 article: http://www.wowwiki.com/Shadowguard?oldid=318304

In case anyone had any doubts.

**Comment by Kaiitothewai** [comment]
There are no doubts about this being a real issue

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nothhelm** [comment]
Hex of Weakness, the Troll spell, doesn't proc it either.
