### ISSUE TITLE
[Hunter] Giantstalker 5-set & T2 bonus breaks autoshot timers

### ISSUE THREAD

**Issue by eralon** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2463]
I am not even sure this is considered a bug but it's a big deal for all hunters that use any autoshot timer addon. Basically, if you have more than 5 pieces of Giantstalker equipped your pet gets the aura "Nature's Ally". For some reason this aura sends a "SPELLCAST_STOP" command every 3 seconds or so. (Found out by using Sorrens hunter timers debug mode)

The "SPELLCAST_STOP" is the same thing all hunter autoshot timer addons use to know when you have fired an auto shot.

Also, the Dragonstalker set has a very similar 5-set bonus and I am almost certain that it also breaks autoshot timers, of course I can't currently test this.

This is indeed the same for Dragonstalker.

**Comment by scs151** [comment]
Like i said in the other issue, this is made by t1/2 5/5 parts(set bonus that buffs pets).   

It breaks all sorts of casting timers, not only autoshot. Mount,Aimed shot even heathstone.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Rulerx** [comment]
Probably related to #4512

**Comment by Forcy** [comment]
Confirmed by Crow

**Comment by Rulerx** [comment]
does this fix also work for #4512?

**Comment by Salce** [comment]
**This went live with Patch 11.2**

**Comment by Rulerx** [comment]
did anyone test this on PTR? still happening on live for me using T2; see #4512 for more detailed report on cast bar disappearance
