### ISSUE TITLE
[SPELL] [PALADIN] Divine Shield / BoP (Making you immune to Bandage Healing)

### ISSUE THREAD

**Issue by datfiyah** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2485]
Abilities such as http://db.valkyrie-wow.com/?spell=1020 and http://db.valkyrie-wow.com/?spell=10278 make you immune to healing by any type of bandages.
Exactly the same as https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2211

**Comment by Kaiitothewai** [comment]
Please report back if this is an issue still, staying close till then !
