### ISSUE TITLE
Dungeon set Tier 2 quest chain broken, unable to summon bosses with "Brazier of Invocation"

### ISSUE THREAD

**Issue by Bicplz** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#25]
Hello there, 

The final item obtained for completing the dungeon tier 2 set chain is not working propperly, and I was unable to summon Lord Valthalak upon completion of the quest chain with the item; "Brazier of Invocation". 

Tried to summon him today, 29.06.16 in the beast room of UBRS. Literally trying to summon him on every inch of the room, nothing worked. 

Please fix this, did this whole long ass quest chain and now I can't help my guild out with summoning the bosses they need. 

Server in question; New Warsong 2.0

Kind regards
Bicplz

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/18
