### ISSUE TITLE
bonus +heal bug after equip swap?

### ISSUE THREAD

**Issue by Excels** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2557]
Hi there,

I just found an issue regarding the bonus heal calulations. In a former Issue it was reported that there is a mistake with the calculation of bonus heal. This was fixed and is not part of this issue. However, there seems to be a bug with the bonus heal after equip swap. This is how I realized it:

I equip my pvp set with 543 bonus heal. Rejuvenation ticks for 364.
Then I swap to my pve gear with 790 bonus heal. Rejuvenation ticks for 414.
Here come the weird part: Now I equip my pvp set again and rejuvenations ticks for 351.
Back to pve set: Reju ticks for 400.

After relogging everything is fine again. However, I can not relog everytime I swap equip and this is for sure not the way it is meant to be. When I was testing this I had the same equipment. I just tripple checked it.

Cheers,
Excelsior, Al'akir

**Comment by Kaiitothewai** [comment]
#4603
