### ISSUE TITLE
[Warrior]Thunderclap threat

### ISSUE THREAD

**Issue by Zulg** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2593]
- [Kenco's Threat Guide] (http://elitistjerks.com/f31/t9258-kenco_guide_threat/) 
- Raw Threat Value for Thunderclap is 130 on successful hit, i.e not counting damage and modifiers from stance. 

On Emerald Dream, Thunderclap is only creating threat from the damage dealt, the fixed value is not applied. It should be (fixed value + damage) making up the total value, just like Heroic Strike. 

Together with Sixt, I tested this today. First Sixt used 5 thunderclaps on a mob for a total of 320 damage(256 threat in battle stance). Adding in the fixed value ((130*0,8)*5) you get 776 threat in this scenario. Another player would then need at least 854 threat to pull aggro. Instead I gained aggro after dealing 386 damage in battlestance, which equals 309 threat. 
 
- [**Screenshot**] (http://img803.imageshack.us/img803/5428/test1th.jpg) after Sixt has used Thunderclap 5 times, note that KTM doesn't include the fixed value either, though this bug also exists with Demoralizing Shout which doesn't show up as creating any threat at all, while it does in fact create threat. 
- [**Screenshot**] (http://img822.imageshack.us/img822/9018/test2bk.jpg) after auto-attacking a few times I pull aggro at a lower threat level than I should be able to. 

Conclusion; Fixed threat is clearly missing on this spell.

**Comment by devidao** [comment]
Fixed

**Comment by Kaiitothewai** [comment]
This was applied with Patch 11.7
http://www.wow-one.com/forum/topic/95872-project-phoenix-1121-changelog-patch-11/?p=730803
