### ISSUE TITLE
[Spell][Priest] Combined Shadow Weaving report.

### ISSUE THREAD

**Issue by Veleant** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2610]
1.Touch of Weakness applies 2 stacks of Shadow Weaving instead of 1. I think that issue occurs because debuff component also applies it, not only damaging part of spell.
![ToW](https://f.cloud.github.com/assets/3968857/301892/1134c9a4-95f0-11e2-949c-25ddb87bd862.png)
2.Vampiric Embrace applies Shadow Weaving, but it is non damaging spell.
![VE](https://f.cloud.github.com/assets/3968857/301920/55155318-95f1-11e2-8499-c03395c49461.png)

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
