### ISSUE TITLE
[shaman] earthbind totem breaks rogue stealth after first pulse

### ISSUE THREAD

**Issue by griesakanik** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2691]
Imported from warsong:https://github.com/FeenixServerProject/Phoenix_1.12_Bugtracker/issues/2306

**how it works**
Earthbind Totem unstealth the rogue every pulse of the totem

**how it should work**
Earthbind Totem must unstealth rogue only  on FIRST pulse, but on Alakir it unstealth with every puls, its actualy bug.

http://www.wowwiki.com/index.php?title=Shaman_PvP_guide&oldid=246410
"Earthbind Totem will unstealth a vanished rogue on its first pulse if the rogue is within range."

http://www.wowpedia.org/index.php?title=Earthbind_Totem&direction=next&oldid=430518
"Currently, the first pulse of Earthbind Totem right after you drop it will bring a rogue out of stealth. Pulses after the first pulse will not bring a rogue out of stealth."

**guide**

make a shaman
.t dev
.learn 15786
.additem 5175
.gm off
.gm visible on
/cast earthbind totem (15786)

make an alliance rogue
.t dev
.learn 1787 (stealth)
.gm off
.gm visible on
/cast stealth (1787)
go near the shaman's totem while being stealthed, you will see that you will get revealed and thats not intended.

**Comment by Nzzoth** [comment]
Issue is still happening on live. Tested and confirmed.

**Comment by Kaiitothewai** [comment]
**Fix is ReConfirmed on PLTR**

**Comment by Kaiitothewai** [comment]
Live.
