### ISSUE TITLE
[Warlock][Hunter][Pet] is not suffering from spell-school lockout effects

### ISSUE THREAD

**Issue by ironsides** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2692]
How they work currently: e.g: if a succubus is counterspelled/pummeled/kicked/etc during their seduction cast, they are able to recast it immediately.

How it should work: they should be locked out of their spell school and forbidden to cast seduction for an appropriate amount of time depending on the interrupt used.

**Comment by Kaiitothewai** [comment]
**Fix is ReConfirmed on PLTR**

**Comment by Kaiitothewai** [comment]
Live.
