### ISSUE TITLE
Sweeping Strikes still not working properly!

### ISSUE THREAD

**Issue by Bigepo** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#27]
Sweeping strikes is supposed to do simular dmg on the sweeping strike as your HIT/CRIT does.
Atm it seems to only be doing a "set amount" of dmg. No matter what your hit/ crit was.
If you crit 2000dmg on ur hit, the sweeping should be somewhere around there too. even higher sometimes.

https://www.youtube.com/watch?v=wrzDZNwmW_k

**Comment by Bigepo** [comment]
![loldmg2](https://cloud.githubusercontent.com/assets/15029321/16516396/235a24a0-3f78-11e6-88cc-b71b6187c029.JPG)

Here is screenshot from Retail vanilla. You see I crit a plate warrior for 1444. and the sweeping HITS a leather rogue for 3228 dmg..

**Comment by Kaiitothewai** [comment]
Correct, there was a great report on the old GitHub subsection

**Comment by devidao** [comment]
Fixed on https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/60
