### ISSUE TITLE
[Quest] Wrong text displayed in Garments of Darkness (Priest class quest)

### ISSUE THREAD

**Issue by seaweedchan** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2704]
This is a quest you get in Brill called Garments of Darkness, where you use Lesser Heal and Power Word: Fortitude on Deathguard Kel north of the cemetery. 

I did it in the following order:
-Casted Lesser Heal on the NPC, and got the text "Heal Deathguard Kel 1/1"
-Casted Power Word: Fortitude on the NPC, and got the text "Heal Deathguard Kel 1/1" again

The text after Power Word: Fortitude should be "Fortify Deathguard Kel 1/1"

**Comment by devidao** [comment]
Unfortunately it is client side issue, i can not fix it. Objectives on DB are not related with text which are showed on the middle screen
