### ISSUE TITLE
Fleeing Mobs

### ISSUE THREAD

**Issue by neo4321** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#28]
It appears that every type of mob that runs in fear is still able to perform certain actions. For example if a mob you were meleeing runs in fear you will still take autoattack damage while running behind it to attack it. Caster mobs running in fear will continue to cast their spells while running aka their cheating by shooting spells out their back while running away and/or healing themselves. I might as well add this here, it may be connected but it appears mobs that use ranged attacks not spells can run while shooting, not in fear but in general they continueously shoot you while running and shoot far faster than they should sometimes triple hitting you in 1 global cooldown.

Extra stuff:
For example Chieftain Bloodmaw (id 9462) still melees while fleeing.
Do a query in the NPC database and replace the faulty script for not stopping attacks after flee stage for all NPCs which still present this with a working script.

**Comment by ender-feenix** [comment]
I am currently unable to reproduce this on our PTR.

**Comment by redmagejoe** [comment]
I've noticed this still happening intermittently, most often with caster mobs who will continue casting heals or bolts while running. There is no, to my knowledge, consistent way to reproduce this.

**Comment by Nzzoth** [comment]
Hello redmagejoe, can you be more specific and tell us on which mobs you encountered this. That applies to everybody that has any information about this.

**Comment by redmagejoe** [comment]
I would have to go and systematically track down every mob and not one-shot them to give you a list. The last mob I can recall this happening with once upon a time was the trolls in STV.

**Comment by ender-feenix** [comment]
Closed for lack of a reproduction guide.
