### ISSUE TITLE
[Quest][Orgrimmar] Betrayed - Wrong level requirement

### ISSUE THREAD

**Issue by rsheep** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2804]
http://database.wow-one.com/index.php?quest=3504

This quest should be available from level 44.
I couldn't accept it at 45.
Reports on "world chat", say that cannot be accepted till level 50.

http://www.aowow.org/?quest=3504
Here, the first quest in the serie, requires lvl50 and this does not make sense at all....seeing that the 2nd in the serie require lvl45.

http://www.wowwiki.com/Quest:Betrayed
From wowwiki the requirement is lvl44

**Comment by Salce** [comment]
Fix applied on live.
