### ISSUE TITLE
[Quest][Thunderbluff] Rabine Saturna - Wrong level requirement?

### ISSUE THREAD

**Issue by rsheep** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2894]
http://database.wow-one.com/index.php?quest=1123

The quest is not acceptable at level 55.
The requirement should be level 54.
"You don't meet the requirements for that quest" appears when you try to accept it, after turning in "The New Frontier" accepted from Warcaller Gorlach in Orgrimmar.

http://web.archive.org/web/20071111023213/http://wow.allakhazam.com/db/quest.html?wquest=1123
http://web.archive.org/web/20070420030851/http://www.thottbot.com/q1123
http://www.wowwiki.com/Quest:Rabine_Saturna_%28Horde%29

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
