### ISSUE TITLE
[Quest][The Hinterlands] Rhapsody's Tale

### ISSUE THREAD

**Issue by hiphopopotamus** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2899]
Turning in the quest [43] Rhapsody's Kalimdor Kocktail is supposed to trigger a dialogue with Rhapsody Shindigger that leads to [43] Rhapsody's Tale. The quest is turned in and the first few lines of dialogue go, but after that you cannot speak with him to get [43] Rhapsody's Tale. Relogging and clearing the cache hasn't been of help.

**Comment by Hairypooter** [comment]
Still bugged and disappointed :(

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Hairypooter** [comment]
Still not working

**Comment by Nzzoth** [comment]
Hello Hairypooter, there is  fix for this issue on PTR. Once it gets updated to live it will be announced in the changelog section on the forum.

Kind regards, Nzzoth.

**Comment by Salce** [comment]
**This went live with Patch 11.0**
