### ISSUE TITLE
Please check it and ban him

### ISSUE THREAD

**Issue by Baekgoo** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#29]
[Edited after issue closed]
I wrote some guys who abused hack and cheat here.
But i wrote it again at hack and cheat board because the article was not proper to the purpose of this board. sorry and thx.

**Comment by Nzzoth** [comment]
Hello Baekgoo,

If you wish to report a player please do it on our forums in Hack & Cheat reports. http://www.wow-one.com/forum/forum/74-hack-cheat-reports/ .Make sure to read all the guidelines before you do.

Issue closed.
