### ISSUE TITLE
[Hunter][Pet] Combat is cancelled after pet hits an npc.

### ISSUE THREAD

**Issue by lauchaseca** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2911]
This problem started shortly after Patch 7 was applied.

Description:

When the pet is sent to attack an npc, and hits once or twice the target, combat is dropped and the pet returns to the hunter. Hits are usually and incorrectly resisted or absorbed by the npc. This situation WILL NOT arise all the time. random mob/random attempt but it happens a lot (and is really disappointing)

Pre-conditions:

Pet is set to defensive/passive stance and following the owner. Both hunter and pet are far enough from the npc so it wont start attacking until pet gets closer or hit it. NPC has a considerable amount of HP, so pet wont one-hit kill it.

How to replicate:

Get any kind of pet, and send it to attack an hostile npc (having growl and claw/bite set to autocast). Hunter must not start auto shot or use any skill at all.

Results:

Pet will hit a couple of times then come back to the hunter, NPC will stop attacking and combat status is cancelled. NPC is reset.

Expected behavior:

Pet continues the attack, casting skills when possible. NPC will attack the pet until killed.

Again, the player must not start autoshot or use offensive skills on the NPC otherwise the fight will develop normally.

**Comment by Kaiitothewai** [comment]
Is this still a issue? report back otherwise it will stay closed
