### ISSUE TITLE
[HUNTER] Can't see Timebar of Spells

### ISSUE THREAD

**Issue by Miano1** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#2933]
Hello there,
I can't see the time which is left if I active the spells "Salve" or "Tame". Thats not a big Problem but if i want to skill my professions like Fishing it is. If i throw the fishing rod into the water I just can see for 1 second how many time is left. The big Problem is there I cant click on the rod so i cant fish any fishes and then i can't skill up my profession. 

Greetings,
Miano

**Comment by Kaiitothewai** [comment]
Please report back if a issue still
