### ISSUE TITLE
[RAID-BLACKWING LAIR] Vaelestrasz the Corrupt is really Corrupted.

### ISSUE THREAD

**Issue by bobblo** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3002]
This screenshot should explain itself.
![vael](https://f.cloud.github.com/assets/2611935/614186/9e4d3132-ce17-11e2-83fb-3146b8fecdbc.jpg)

If not, i will explain it for you.  Vael somehow aggroed while still being neutral.  All is well, except that he doesnt give us Essence of the Red, the debuff that makes this fight doable.  Hate to say it, but maybe Blackwing Lair needed more testing.

**Comment by Salce** [comment]
Fix applied on live.
