### ISSUE TITLE
[QUEST] The Ruins of Stardust Dialogue Bugged

### ISSUE THREAD

**Issue by goody9302** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3149]
After completing "The Ruins of Stardust." the following dialogue should happen but it doesn't.

Pelturas Whitemoon places a poultice on Relara's brow.
Pelturas Whitemoon breathes a sigh of relief.

This is bugged and needs to be fixed.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
