### ISSUE TITLE
[QUEST][DM] Unfinished Gordok Business

### ISSUE THREAD

**Issue by warchieflj** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#32]
Unable to find the Prince's chest which contains [Gauntlet of Gordok Might].The chest is supposed to be near the Prince in DM library
link for the quest item http://www.wow-one.com/database/?object=179545

**Comment by Kaiitothewai** [comment]
This is sort of a duplicate of #26 afaik

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/26
