### ISSUE TITLE
Priest MindVision Rank2

### ISSUE THREAD

**Issue by Blackpearl1** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3270]
The Priest Spell "Mindvision" (Rank2) don't work blizzlike.

On original Blizz Vanilla the Priest don't need to be in line of sight to the Target to use Mindvision Rank2
Only need to have it in your Target.

On ED(Vanilla) you can't use Mindvision Rank2 because you become the message "Target not in Line of sight".
That is not the right functionallity of this Spell.

btw.: I tell this issue already some month ago, but I can't find it now... why?
It's a verry annoying Problem because ths make the Spell nonsense.

Extra
Priest mind vision doesn't work properly when used on range above 36 yards (DOESN'T WORK AT ALL)

Priest spell ~ Mind Vision bugs every time when target resists and Mind vision cannot be resisted. On successful resist, you gain buff Mind vision that lasts 60 seconds and you cannot cancel it or use Mind vision spell again. You do not get vision of that target which is obvious.
Screenshot bellow.

http://i.imgur.com/2ldto16.jpg

More here.
http://www.wowwiki.com/Mind_Vision

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Blackpearl1** [comment]
What means "Fix denied on PTR"? Its not allowed to Fix this Bug on the PTR? I'm confused.

**Comment by Cabro** [comment]
It means that the fix that the devs put on PTR has been denied (it didn't fix the bug).

**Comment by Blackpearl1** [comment]
Ahhh oka :/
thx

**Comment by devidao** [comment]
Fixed, latest my fixes were not applied somehow

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
*This went live with Patch 11.2**
