### ISSUE TITLE
[ITEM] Gnomish Net-o-Matic Projector (ID10720) shouldn't break on damage

### ISSUE THREAD

**Issue by Maktaz** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3458]
**Current situation**

The net from the Gnomish Net-o-Matic Projector **[Spell-ID 13120]** breaks on damage or breaks early.

**Desired situation**

The net shouldn't break on damage, it should last the full 10 seconds at all times.

*Source: http://www.wowhead.com/item=10720#comments:id=414016*

**Comment by ender-feenix** [comment]
The comment which claims that it does not break on damage is from wotlk.  Does anyone have any evidence from closer to vanilla that verifies this issue?

**Comment by Black-Light** [comment]
https://www.youtube.com/watch?v=c4bgggKMvQU 8:45

**Comment by ender-feenix** [comment]
In other words you think we should never double check anything?

**Comment by Kaiitothewai** [comment]
**Fix is ReConfirmed on PLTR**

**Comment by Kaiitothewai** [comment]
Live.
