### ISSUE TITLE
[Hunter] Improved wing clip / Counterattack Root breaks on damage

### ISSUE THREAD

**Issue by Flovin** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3519]
The root effect from Imp wing clip and counterattack has a chance of breaking upon damage/damage threshhold. 
http://database.wow-one.com/index.php?spell=20910
http://database.wow-one.com/index.php?spell=19235

Atleast counterattack should be guaranteed 5second root. 

http://vanilla-wow.wikia.com/wiki/Counterattack

**Comment by scs151** [comment]
This is still bugged on ED. Since the patch was removed.

**Comment by Kaiitothewai** [comment]
**Fix is ReConfirmed on PLTR**

**Comment by Kaiitothewai** [comment]
Live.
