### ISSUE TITLE
[Bug] Pet's initial attack resets aimed shot "channeling"

### ISSUE THREAD

**Issue by ghost** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3525]
So, I issue I've been facing after the core merge. I find a mob, send my pet in and start a aimed shot "channeling". If the pet gets to the mob BEFORE my aimed shot is fired, my aimed shot is cancelled, no CD and no shot actually fired, so my hunter resets with a new auto-shoot swing.

Is this something new, or is it just me? There might be some addon conflicting, but I have never had the issue before and haven't changed addons since the merge.

**Comment by Kaiitothewai** [comment]
Report back if anybody has this issue.
