### ISSUE TITLE
[Class][Spell] Different spellranks cannot be applied to the same target simultaneously by two different priests..

### ISSUE THREAD

**Issue by Maktaz** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3544]
**Current Situation:**

When two priests are fighting a mob they are unable to use different ranks of the same spell on a target.

For instance, *Priest A* casts Mind Flay rank 5, then *Priest B* casts Mind Flay rank 4 on the same mob. The Mind Flay that was first cast (in this case rank 5) get's pushed off. *Priest 1* will still be channeling his Mind Flay, but he won't do any damage.

The same goes for Shadow Word Pain, the first one gets overwritten if different ranks are used. I am not sure it applies to other spells as well (didn't test it for other spells).

I think this is caused by the mechanic that prevents one priest from casting multiple ranks of the same spell on a target, however, different priests should be able to cast different ranks on a target just fine.

**Desired situation**

I believe both ranks of the spell should be applied to the target if they come from different sources.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Rulerx** [comment]
Q: does the fix effect all dots/hots or just priest dots/hots?

**Comment by Salce** [comment]
**This went live with Patch 11.0**
