### ISSUE TITLE
[CORE] Kel'Thuzad, Hakkar, Chromaggus, Skeram and more (Mind Control Teleport) (MC Teleport)

### ISSUE THREAD

**Issue by Pyritie** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3693]
**Kel'Thuzad**
Once Kel'Thuzad uses his Mind Control ability, he will teleport ontop of them and make the encounter impossible.

**Hakkar** 
Once Hakar uses his Mind Control ability, he will teleport ontop of him and make the encounter more annoying.

**Skeram**
Once Skeram uses his Mind Control ability, he will teleport ontop of him and make the encounter very annoying.

**Chromaggus**
If a player is transformed into a hostile drakonid when they get all 5 of Chromaggus' brood afflictions, Chromaggus begins to teleport around the room. It looks like he regularly teleports to wherever the transformed player is at the time, at regular intervals of a second or two.

EDIT:
This means that if someone gets all 5 then it's a wipe since you can't control chrom any more. Although a good guild should never let this happen, you should still be able to recover from it (killing/sheeping/etc the player). Currently this is not possible.

**Comment by Rulerx** [comment]
Any developments on this?

**Comment by Kaiitothewai** [comment]
This is Live.

**Comment by Kaiitothewai** [comment]
Live.
