### ISSUE TITLE
[BWL] Razorgore and egg counting

### ISSUE THREAD

**Issue by Pyritie** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3694]
It looks like the "30 eggs destroyed" requirement for razorgore to enter his final uncontrollable phase uses some sort of internal counter for how many times his "Destroy Egg" spell was successfully cast instead of how many eggs have actually been destroyed.

Yesterday we had an issue where one of the eggs would not disappear after using Destroy Egg on it twice. On the third attempt (when he was controlled by a different player), the egg was "destroyed". Razorgore entered his final phase when there were still two eggs left, which makes me believe that those two attempts actually DID count towards the total.

**Comment by Salce** [comment]
Fix applied on live.
