### ISSUE TITLE
[Shaman] Chain heal bounces with wrong formula.

### ISSUE THREAD

**Issue by Kowbus** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3708]
Hi there, after several test with some other shaman from my guild we found out that the bounces on chain heal spell were taking too much + healing.

-How it is currently : Chain heal on first target = spell base heal + 71.4% of the + heal from gear, 1st bounce healing half of the initial healed (including the 71.4% heal bonus from gear) +~35.7% of the +heal from gear, 2nd bounce is half of the 1st bounce +~35.7% of the +heal from gear.

-How it should be : Chain heal on first target = Spell base heal + 71.4% of the heal bonus from gear, 1st bounce has it down to 50% of the total healed from the initial heal(i guess the real formula would be 50% of the base spell initial heal(606-692(including 10% from talent) if we talk about R3 CH) + 35.7% of the +heal bonus from gear) and 2nd bounce being 50% of the 1st bounce (so 25% of the base spell initial heal +35.7% of + healing bonus from gear).

The 3bonus piece from T2 (+ 30% heal on chain heal bounces) works just fine.

The result of the current pattern would lead, with the adequate gear (naxx ~ and 3 t2), to have bounces able to surpass initial heal from CH, without crit. Making CH R1 disbalanced since it takes the same amount of +heal from gear than other 2ranks (wich is as it's supposed to be). It would change the shaman itemisation and the healing equivalence of stats for the class.

Here is a video where you can clearly see how it worked back in vanilla retail, just keep in mind that this shaman has around a minimum of 650+ healing and 3pieces t2. http://www.youtube.com/watch?v=HUzWiQF1fMg 1:10 you can clearly see the heals from his max rank chain heals.

The heals from his chain heal are : 1157 > 725 > 473.
1157/2 = 578.5 + 173.55 (30% of it (3 t2 bonus)) = 752.05 (1st bounce)
725/2 = 362.5 + 108.75 (30 of it 3t2 bonus)) = 471.25 (2nd and last bounce)
Wich matches with the formula i wrote above.

I hope this was clear enough, don't hesitate telling me if you need more claryfication, details or anything else. Cheers =)
http://elitistjerks.com/f47/t19038-spell_coefficients/ for the Coefficients on heals.

**Comment by ender-feenix** [comment]
This went live again, so closed!
