### ISSUE TITLE
[NPC] The Barrens: Razormane Stalkers are not stealthed

### ISSUE THREAD

**Issue by netherspite** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3765]
Razormane Stalkers in The Barrens are supposed to be stealthed, however they are not.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
