### ISSUE TITLE
[Priest] Oracular Heal not proccing off of Vampiric Embrace

### ISSUE THREAD

**Issue by Snorty** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3798]
[Current Situation]: When I use Vampiric Embrace on an enemy, I do not receive the extra amount of healing from my 3 piece 2.5 Oracle set. For instance, when I use Shadow Word: Pain (Rank 8) on an enemy, who is also inflicted with Vampiric Embrace, I do not receive any bonus healing for myself due to wearing the 3 piece Oracle set bonus.

Say for example, my Mind Blast Rank 9 does 1000 damage. I first use Vampiric Embrace on my enemy target (not specced into Improved Vampiric Embrace and not including Shadow Vulnerability), and then my next spell I use is Mind Blast Rank 9 that does 1000 damage. The amount of healing I should receive is 200 (due to Vampiric Embrace granting me 20% healing of the full amount of damage I deal.)

The problem is when I have my 3 set bonus of Priest T2.5 on as well. Due to the nature of the spell, any healing that I do will have a 20% chance to give me a 10% increase in healing. So, when my 3 set bonus procs (going back to the example given above) if I use a 1000 damage Mind Blast, not only should I receive the initial bonus from Vampiric Embrace (the 200 healing), but also 10% added onto that 200. Therefore, the total amount of healing I should be receiving is 220.

Screenshot of the 3 Set Oracle bonus:
http://www.wowwiki.com/Garments_of_the_Oracle

Screenshot of Vampiric Embrace:
http://db.valkyrie-wow.com/?spell=15286

Screenshots of myself (Snort) and Herbmann in a party using different shadow spells with Vampiric Embrace active on targets. The reason for these screenshots is to prove I tried multiple times to proc the 3 set bonus, but it would not. Each time Snort and Herbmann recieved the exact amount of healing from Vampiric Embrace even while I was wearing my 3 set Tier 2.5 gear.
http://i.imgur.com/qIlKl2J.jpg
http://i.imgur.com/srNWHz2.jpg
http://i.imgur.com/7VMWQAq.jpg
http://i.imgur.com/6o3Pqdo.jpg
http://i.imgur.com/0AM5Mi7.jpg
http://i.imgur.com/hqcmfzf.jpg
http://i.imgur.com/w6okoTj.jpg
http://i.imgur.com/mx2EPRI.jpg
http://i.imgur.com/x8A6d1B.jpg
http://i.imgur.com/cSn0QJV.jpg

Screenshots of the 3 pieces of Tier 2.5 I am using for proof reasons (the head, the boots, and the shoulders):
http://i.imgur.com/Ddr7rn0.jpg
http://i.imgur.com/XXQXZqx.jpg
http://i.imgur.com/gZbdTrZ.jpg

Thank you very much Feenix for your support. I sincerely hope this issue gets resolved in a timely fashion! Thank you so much for your unrelenting effort and kindness! If you have any more questions about my methods or any other questions for me, please let me know!

Snort, Level 60 Shadow Priest, Al' Alkir

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
