### ISSUE TITLE
Supply Crates in Stratholme (is not Stratholme Supply crate) -----    A B U S E

### ISSUE THREAD

**Issue by griesakanik** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3837]
http://www.wowwiki.com/Supply_Crate_%28Stratholme%29

GOBJ = 176224 (no title) ON PTR
GOBJ on wowhead = http://www.wowhead.com/object=166872

Please be sure to get the right ID.

The following gobj should have these following attributes:

* No respawn timer, because they despawn after 5 minutes when they are once opened , or the loot is taken, they should despawn for the whole instance id; OR please set an incredible high respawntimer to prevent abusing.

* 25% To contain the loot given in the database.
* 25% To contain no loot at all
* 25% To contain no loot at all and  cast http://www.wowhead.com/spell=16432 on you.
* 25% To contain no loot at all and spawn ~5 of one type of the following npcs 

http://www.wowhead.com/npc=10461 (Spell ID: 16369)
http://www.wowhead.com/npc=10536 (Spell ID: 16370)
http://www.wowhead.com/npc=10441 (Spell ID: 16371)

http://de.wowhead.com/object=166872/#english-comments

> On live realms the Obj provides 90% Loot and has a 15(?) minute respawn timer, i believe it's even less.

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
