### ISSUE TITLE
Magram Scouts are defenseless if attacked from 35 yds

### ISSUE THREAD

**Issue by netherspite** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3845]
Magram Scouts ( http://database.wow-one.com/index.php?npc=4638 ) does not attack you or move to you if attacked from 35 yards distance.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
