### ISSUE TITLE
[Quest] Bijou's Belongings

### ISSUE THREAD

**Issue by 0vertime** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3850]
Blackrock Spire (Lower)
http://database.wow-one.com/index.php?quest=5001 (Alliance)
http://database.wow-one.com/index.php?quest=4982 (Horde)

Currently the object "Bijou's Belongings" does not spawn or is not visible.
http://database.wow-one.com/index.php?object=175334

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
