### ISSUE TITLE
[ZG] Jin'do The Hexxer (Brainwash Totem) - Emerald Dream

### ISSUE THREAD

**Issue by Nain1** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3956]
When players are mind-controlled by Jin'do the Hexxer's Brainwash Totem (npc 15112),  the ability that the Brainwash Totem casts, and it's subsequent effect (24178) doesn't align the player with Jin'do the Hexxer; this allows Jin'do the Hexxer to attack players who are mind-controlled under the effect of 24178.

Becoming the minion of 15112 should align players with Jin'do the Hexxer.

**Comment by Salce** [comment]
Fix applied on live.
