### ISSUE TITLE
[QUEST] Outrider Basic Care Package

### ISSUE THREAD

**Issue by rudacris** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#3980]
This quest (ID=7866) should only be available to level 25 horde characters with friendly or better reputation with Warsong Outriders. I was able to complete the quest at 19/neutral.

Source: http://www.wowhead.com/quest=7866

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
