### ISSUE TITLE
Glancing blow chance (SHAMAN ONLY)

### ISSUE THREAD

**Issue by surelynotdhorn** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4016]
After the recent glancing blow fix ( https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/3929 ), shamans appear to have an unusually high chance for glancing blows. This is likely caused by implementing glancing blows as described in http://www.wowwiki.com/Weapon_skill?oldid=349293 and classifying shamans as a non-melee class, effectively giving any shaman above level 30 a glancing blow chance around 60%. Hybrid classes should most certainly be considered melee classes as they all have some form of intended melee-based playstyle (feral, enhancement, retribution) and would suffer tremendously from a 60% glancing blow probability. Chances are I'd also be able to find people crying about that being the case on elitistjerks but I can't ( https://www.google.com/search?q=site%3Aelitistjerks.com+60%25+glancing+blow&biw=2001&bih=772&sa=X&ei=ZVm_Uu-RFMLOtQaO3oDYBA&ved=0CBsQpwUoBg&source=lnt&tbs=cdr%3A1%2Ccd_min%3A%2Ccd_max%3A12%2F5%2F2006&tbm=#q=site:elitistjerks.com+%2260%25%22+glancing+blow&tbs=cdr:1%2Ccd_max:12%2F5%2F2006 ).

While this is only confirmed to be a problem for shamans, but it's entirely possible that paladins and druids are affected as well

**Comment by ender-feenix** [comment]
The fix for this has actually been live for a while now.
