### ISSUE TITLE
[Rogue] Combopoints lost when finisher misses.

### ISSUE THREAD

**Issue by igothair** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4043]
When expose armor finisher misses it consumes all combopoints.

Here is a video documenting the bug.
http://www.youtube.com/watch?v=u3_n5QbYq-s&feature=youtu.be

(it does not happen all the time, but often enough to be a problem)
Edit: Here is some combat logs showing the difference between when it loses combo points and when it does not lose em.

Successfull expose armor: 
You hit wastewander thief for 34.
You hit wastewander thief for 82.
Wastewander theif attacks. You dodge.
You gain 25 energy from relentless strikes effect.
Wastewander thief is afflicted by expose armor.
You hit wastewander thief for 35.
Your hemorrhage hits wastewander thief for 110.

Unsuccessfull expose armor(combo points not used):
You hit wastewander badnit for 15. (20 blocked)
Your expose armor is parried by wastewander bandit.
You gain 25 energy from relentless strikes effect.
You crit wastewander bandit for 184.
Wastewander bandit attacks. You dodge.

Unsuccessfull expose armor(combo points is used):
You miss wastewander thief.
You hit wastewander thief for 81.
Your expose armor missed wastewander thief.
You hit wastewander thief for 32.
Wastewander thief hits you for 67.

**Comment by Salce** [comment]
Fix applied on live.
