### ISSUE TITLE
rogue poison quest

### ISSUE THREAD

**Issue by jeffroyswift** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4064]
i have tried to do the poison chain quest for rogue. at the step of the tower i died so many time and drop the quest and delete all item for this quest( whistle ,flare etc)

now i want to have my poison (im lvl 30) and i cant get the quest anymore. i have open a in game tiket and gm say to come here.

i have explored all forum, talk with alot of rogue,,,,,no one know what to do help me plz

carater name: saloppe (emerald dream 1x horde)

**Comment by Kaiitothewai** [comment]
#798
