### ISSUE TITLE
[Mage] [Talent] Combustion.

### ISSUE THREAD

**Issue by Raudram** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4119]
This is about the spell critical chance, sometimes I get a ridiculous amount of stacks and my spells still don't crit, I've had 10 stacks plus very high base crit chance and multiple spells on a row didn't crit. No idea if this is related to combustion or spell criticals in general.

**Comment by Kaiitothewai** [comment]
I think this is RNG.
