### ISSUE TITLE
[Druid] [Item] Idol of the Moon (Trinket) NOT adding 17% damage to Moonfire

### ISSUE THREAD

**Issue by roamsquad** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4202]
http://db.valkyrie-wow.com/?item=23197
Is a link to it. 
I ran a test to see if the damage was increased, (using gear set with +0 sp) the actual instant damage remained right around the same, and my dot always ticked for same amount, whether idol on or not.

Idol on: Instant: 230-260
                 DoT: 113 / tick
Idol off: Instant: 230-260
                 DoT: 113/ tick

![idolon](https://f.cloud.github.com/assets/6897283/2367708/5e1474de-a776-11e3-8543-b3d6ea3820f8.jpg)
![idoloff](https://f.cloud.github.com/assets/6897283/2367709/5e14f72e-a776-11e3-9cf7-6b2ec15576f6.jpg)

As you can see, the damage is identical.
Please fix

**Comment by redmagejoe** [comment]
Any news? #boomkinstruggles

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Salce** [comment]
**Fix confirmed on PTR**

**Comment by redmagejoe** [comment]
So there's a changelog that says that this has been fixed, but this thread is still open and I haven't been able to find anyone in-game who can confirm the fix.

Is this fixed?

**Comment by Nzzoth** [comment]
Fix is live with patch 11.8
