### ISSUE TITLE
polymorphed hunters pet dont get hp regeneration

### ISSUE THREAD

**Issue by robbywow1** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4218]
polymorphed hunters pet dont get hp regeneration

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Forcy** [comment]
If polymorphed pet starts regenerating health as if it's out o combat. Which is like 60 health per Instead it should be like 1 second - Full health
In the same way Polymorph regens HP to players and enemy creatures

**Comment by Forcy** [comment]
Refixed and confirmed

**Comment by Salce** [comment]
**This went live with Patch 11.2**
