### ISSUE TITLE
Ruklar the Trapper @ gluth

### ISSUE THREAD

**Issue by Zulako** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4221]
Ruklar the trapper running around hitting healers specifically for 2k HP a second on gluth. http://i.imgur.com/yd6A6n6.jpg

There have been reports of this happening to guild runs in AQ40 too.

This is an odd bug for sure, and is certainly not blizzlike =p

**Comment by Nzzoth** [comment]
This is no longer an issue on live. Closed.
