### ISSUE TITLE
Multi-Shot Issue

### ISSUE THREAD

**Issue by Joymee** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4249]
Multi shot puts main hand melee attack on cooldown. When you use multi shot you can't immediatly auto attack and thus raptor strike. This is not blizzlike.

**Comment by scs151** [comment]
Sadly until this is fixed 2-hand weapons are useless in PVP. Since you have to wait ~3.5ish seconds for that raptor strike and at that point your target is far away.

**Comment by Goanno** [comment]
Fix confirmed on PTR

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
