### ISSUE TITLE
[Spell Fear/Psychic Scream] [Targets attack/Cast spells under effect]

### ISSUE THREAD

**Issue by Mofoleone** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4276]
Players and NPCs while under fear spell they "sometimes" can attack and cast spell totally ignoring that they are under fear effect.
Why I wrote "sometimes" because it doesn't happen every time.

**Comment by devidao** [comment]
Can not reproduce this

**Comment by Nzzoth** [comment]
A fix for this has been live for some time, if somebody encounters it please post here.
Closed.

**Comment by Cabro** [comment]
Is the fix viable only for fear effects or for flees too?

**Comment by Nzzoth** [comment]
It is for all crowd effects that behaved that way. This was fixed when KT was released.

**Comment by Cabro** [comment]
So only for fears. Because for flees they still attack/cast spells.

**Comment by Nzzoth** [comment]
Make a seperate issue about it read the title that is a different issue what you described.

Kind regards.
