### ISSUE TITLE
[Raid][Naxxramas][Gluth] Debuff from adds

### ISSUE THREAD

**Issue by disho** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4279]
Sometimes debuff stacks from gluth adds do not work on plate tanks, so they take just 1-200 hits and can tank spank em.

**Comment by Nzzoth** [comment]
This issue was indirectly fixed when the proc on hit on targets with absorb effect went live.
Closed.

**Comment by killerduki** [comment]
it's not only absorb

block/parry/dodge/miss doesn't reapply it too
