### ISSUE TITLE
Priest Mindcontrol Wall Walk Bug

### ISSUE THREAD

**Issue by Kandin** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4303]
This is a bug that allows players who have been mind controlled to have wall walking turned on. It is very detrimental to play and should be fixed asap! I've personally had it happen to me on 4 separate occasions now. The key factor between each time i've had wall walking enabled was a mindcontrol by a priest, usually thrown out of either a battleground or a portal/instance of some sort. Once out of the battleground/instance (and usually killed by horde npcs because of faction switch bug) you will not be able to emote anymore, but you will be able to walk up almost vertical walls. I've even been BANNED for this bug, so please do something about this.

PS. i would post a screenshot, but i feel as if the gms would figure me hacking and ban me anyways -_-

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by ender-feenix** [comment]
The fix for this went live with the war effort.
