### ISSUE TITLE
[PRIEST] [SPELL] Mindcontrol Bug

### ISSUE THREAD

**Issue by lokol99** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4315]
Edit : Removed to prevent abuse, thank you for the report.

http://www.wow-one.com/forum/topic/79058-mind-control-issue/

**Comment by Nain1** [comment]
bump

**Comment by Nain1** [comment]
This is still crashing the server quite often.

**Comment by ender-feenix** [comment]
There was a miss-communication about how the fix for this was supposed to work.  It has since been tested and confirmed by @Nzzoth .

**Comment by Nzzoth** [comment]
Hello, as Ender stated there was some miscommunication. The following issue is tested and confirmed on PTR.

**Comment by ender-feenix** [comment]
After some internal cleanups, this needs to be re-tested on the PTR.

**Comment by Kaiitothewai** [comment]
**Fix is Confirmed on PTR**

**Comment by Kaiitothewai** [comment]
Live.
