### ISSUE TITLE
[WORLD BOSS] Emerald Dragons are not respawning

### ISSUE THREAD

**Issue by PlaskED** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4335]
It has been noted that there has been no spawn of Emerald Dragons the last 8 days. It seems like they completely stopped spawning. Kinda hard to provide proof for this but I guess it could be checked up from the developers/GM's.Last known death was the 25th May I believe.

**Comment by Soyoen** [comment]
Stated to have been fixed, still awaiting spawn after the spawn window has been passed (168 hours). Will update at/if spawn.

**Comment by Kaiitothewai** [comment]
You are aware the servers had several hours of downtime?

**Comment by Soyoen** [comment]
Spawn. ~27 hours of downtime seems a bit excessive but yes.

**Comment by Kaiitothewai** [comment]
No.
