### ISSUE TITLE
[Raid][Blackwing Lair] Nefarian - Priest call

### ISSUE THREAD

**Issue by Mofoleone** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4415]
Priests are afflicted with Corrupted Healing, causing the targets of any direct heals they cast to be debuffed by Corrupted Healing, dealing 44 to 56 damage every 1 sec, stacking up to 50 times.

Spells that trigger Corrupted healing
http://wowhead.com/spell=23401#modifies

Situation on Emerald Dream:
When Vampiric Embrace is applied to Nefarian:
Healing ticks from Mind Flay apply Corrupted healing.
Since Mind Flay can be classified as DoT  but it's channeling spell and healing done by Vampiric Embrace is not direct healing (just by nature of Mind Flay)
shouldn't proc corrupted healing on your targets.

Shadow priest mechanics when it comes to healing from Vampiric Embrace didn't got changed in any expansion, and can be seen in various solo-sp Nefarian kills on youtube.

One proof here.
https://www.youtube.com/watch?v=Z3BNXjW1txA
2:38

This time please, instead of closing and calling not enough proof, would be nice if someone with higher knowledge of this game can take a look.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
