### ISSUE TITLE
[Rogue] Stealth attacks causing mobs to run, reset, and attack

### ISSUE THREAD

**Issue by AshAkiri** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4441]
This one popped sometime between 19 July and 20 July. Emerald Dream. Only appears to be a problem when attacking in stealth.
https://www.youtube.com/watch?v=bP2sW56Rwdw

Note: I was attacking these same mobs yesterday without issue

**Comment by Kaiitothewai** [comment]
Report back if this is the same still.
