### ISSUE TITLE
[Rogue] mobs get out of combat after stunlock

### ISSUE THREAD

**Issue by ElderSman** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4444]
After stunlock or just cheap shot if u are out of melee distance when stun overs, mobs leave combat and fully regen hps. Its realy annoying when I fight elite mobs and break distance after stunlock to regen energy and now I must stay in melee zone and get extra hits to do not have mob be regened to full hps.
This bug appeared in last few days.

**Comment by Kaiitothewai** [comment]
Please report back if this is the same.
