### ISSUE TITLE
[Item] [Spell] Wrath of Cenarius is not proccing from mind flay or shadow word: pain

### ISSUE THREAD

**Issue by lanfeare** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4539]
The item:

http://database.wow-one.com/?item=21190

 Wrath of Cenarius is not proccing from either mind flay or shadow word: pain.  Wowhead comments indicate that it is supposed to proc from dot ticks and the ticks of channeled abilities:

http://www.wowhead.com/item=21190

The 1.12 patch notes also indicate that it was fixed to work with arcane missiles, which is a functionally similar spell to mind flay:

http://www.wowwiki.com/Patch_1.12.0

This can be tested on the PTR by:
-creating a level 60 priest with the talent mind flay
-equipping the item (http://database.wow-one.com/?item=21190)
-using shadow word: pain and mind flay a significant enough number of times to have been able to proc it beyond the shadow of a doubt

Thanks

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
