### ISSUE TITLE
[Class Quest] [55+] Kroshius' Infernal Core

### ISSUE THREAD

**Issue by wow-config** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4544]
Kroshius Kroshius is reanimated when you get there but as a corpse that cannot attack but only follow...

i soloed this at lvl 52 with my wand since he couldnt attack since he is just a bunch of rubble and when i asked other warlocks then i was informed they all knew this bug was there but hadnt yet been fixed.

please fix this since it is a class quest and it grants 1 of the final guardian pet summoning spells for warlocks .

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
