### ISSUE TITLE
[Hunter] LoS issues with every pet-targetted spell

### ISSUE THREAD

**Issue by Blaqwar** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4584]
Posting this because of #3260.

Line of sight bug is affecting Mend Pet, Dismiss Pet, Feed Pet and Intimidation, along with the fixed Bestial Wrath. The mentioned abilities trigger GCD, go on cooldown (if applicable), consume mana and reagents (if applicable) but have no further effect.

**Comment by devidao** [comment]
Fixed

**Comment by Kaiitothewai** [comment]
**Denied on PTR**
* Dismiss Pet does not work through Line of Sight

**Comment by Forcy** [comment]
Fixed with patch 11.7

**Comment by Kaiitothewai** [comment]
This was applied with Patch 11.7
http://www.wow-one.com/forum/topic/95872-project-phoenix-1121-changelog-patch-11/?p=730803
