### ISSUE TITLE
[WARLOCK] Improved Firebolt talent rank 2 not working

### ISSUE THREAD

**Issue by nxsofsys** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4601]
WIth Improved Firebolt talent rank 2 imp casts spell 1.5 sec. instead of 1 sec, but in tooltip for spell cast time shown as 1 sec.

By http://www.wowwiki.com/Imp?oldid=325379

>The Imp uses up lots of mana on this attack and won't use Firebolt again until it has the mana to. It takes the Imp 2 seconds to cast the Firebolt ability. It can be improved to 1 second through the Improved Firebolt talent (This was finally fixed in Patch 1.12).

**Comment by devidao** [comment]
Tested on PTR and works correct for me, anyone can confirm this issue?

**Comment by Nzzoth** [comment]
Tested on PTR and it works as intended. Issue closed.
