### ISSUE TITLE
Kel'thuzad's Mana detonate.

### ISSUE THREAD

**Issue by Pagatha** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4697]
Kel'thuzad's mana detonate does not reduce the mana of the affected target by 50%.

Sources: http://www.wowwiki.com/Kel'Thuzad_(original)
- A debuff randomly applied to a mana using player. The player will explode after 4 seconds, dealing Arcane damage based on maximum mana to all players within 10 yards (not to himself). This will burn half of their current mana pool. This spell has a 20 second cooldown.

 http://wowpedia.org/Kel'Thuzad_(original)
- A debuff randomly applied to a mana using player. The player will explode after 4 seconds, dealing Arcane damage based on maximum mana to all players within 10 yards (not to himself). This will burn half of their current mana pool. This spell has a 20 second cooldown

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
This is live. Closed.
