### ISSUE TITLE
Aimed Shot and Multi Shot bonus damage not affected by base modifiers

### ISSUE THREAD

**Issue by ender-feenix** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4698]
The +600 bonus damage from aimed shot is incorrectly ignoring base damage modifiers (i.e. ranged weapon specialization).

Edit: Total damage modifiers such as humanoid slaying, etc. are applied.

**Comment by Zecov** [comment]
Is a new fix something that has a small prio on your list, or is it something we should expect to happen in the far far future, if ever?

**Comment by Nzzoth** [comment]
Hello Zecov, this is not a forum therefor we don't discuss such things openly here, please restrain yourself from asking such questions.

**Comment by ender-feenix** [comment]
While this is not always the case, we often will assign priority to re-fix fixes that are incomplete or incorrect before moving on to new things.  It helps to keep things more neat and orderly on our side.  So, while I cannot tell you a date, I imagine this will be re-fixed sometime soon.

**Comment by Zecov** [comment]
Alright, thank you for the quick and precise answer :). Hopefully this is something that can get fixed one day ;)

**Comment by ender-feenix** [comment]
Note that the reason unexpected results were obtained on the PTR seems unrelated to this fix, so we will have to investigate what is going on in general.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by ladnopivo** [comment]
one good proof how full t1 hunter doing smiliar dmg like full t3 hunter on warsong in pvp
https://www.youtube.com/watch?v=fK5a3mBxiFA
you can check date of this video on warcraft movies site which link is posted down of original youtube video..for lazy ppl date is 2006-09-29

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
