### ISSUE TITLE
Rogue Ability issue

### ISSUE THREAD

**Issue by Alyaseen** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#47]
I cant cast spell "Blind",but i have blinding powder,when i try to cast it on someone,it doenst work,and after that i cant use any other ability,and it pops red text "internal error",i tryed deleting cache wtf wdb and stuff,it didnt helped me,charachter Elmaa,alliance female human

**Comment by Kaiitothewai** [comment]
Sounds odd. You should contact somebody on the forum i think.

**Comment by Alyaseen** [comment]
Hello i fixed problem by equiping item in ranged weapon slot,that was thing which was making this error.
