### ISSUE TITLE
Instant WSG flag capture near the alliance roof

### ISSUE THREAD

**Issue by Namatrials** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4703]
![wowscrnshot_093014_184309](https://cloud.githubusercontent.com/assets/8981046/4471276/165b5028-4937-11e4-8b17-e91ed7a8a95b.jpg)

There is a temple-like building on the right side of the ramp leading up to the alliance roof where sometimes alliance players with the horde flag hide behind. Standing behind this building, as a FC, while the alliance regains the alliance flag from the Horde, results in an instant flag capture for the alliance without the FC even moving close to the actual flag spot. This accured not only to me but also other players and seems to be relativley new since noone else I asked knew about it. Happened on Feenix - Al'akir.

**Comment by ender-feenix** [comment]
The fix for this has been live for some time now.
