### ISSUE TITLE
[Druid] Mobs Evade when Attacked while Prowling

### ISSUE THREAD

**Issue by Ragepaw** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4757]
Approximately 55% of the time, when I (experienced since level 20, now level 41) attack a mob of my level range, with either ravage or pounce, they evade to a spot a few yards away, heal to full health, and drop all bleeds/debuffs I've applied.  This of course breaks me out of prowl, and I'm forced to fight them from full health, in front of them, which really puts me at a tremendous disadvantage.

The mobs seems to maybe be running back to the origin of their pathing, but that is just speculation.

I am a Night Elf.

**Comment by Kaiitothewai** [comment]
Please post here agian if this is a issue still, staying closed otherwise
