### ISSUE TITLE
[Quest] Knowledge in the Deeps

### ISSUE THREAD

**Issue by Eonall** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4791]
The chest can only be looted by one player before disappearing. Can't find anything to suggest that it should not be lootable multiple times. Seems ridiuclous that you would have to make 5 trips to BFD simply in order to all finish this quest.

Was wondering if anyone can confirm if this is Blizzlike or not. In the meantime I will keep searching for info.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
