### ISSUE TITLE
[Quest] Mage Summoner

### ISSUE THREAD

**Issue by Eonall** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4792]
Sarilus Foulborne attacks only with melee.

http://www.wowwiki.com/Sarilus_Foulborne

Should summon elementals and attack with frostbolt

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
