### ISSUE TITLE
OOX-22/FE Distress Beacon Drop Rate

### ISSUE THREAD

**Issue by goody9302** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4794]
The Distress beacon for the Feralas OOX escort quest seems to be an extremely low drop rate.  I had killed hundreds of gnolls in the area, and not a single drop.  I had also quested through the entire area on both my horde and alliance characters, and all without a single mob dropping the quest.  I don't know if this is intended, but I don't believe the drop rate should be this low.  If someone could look into this, I would appreciate it.  Thanks.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**

**Comment by goody9302** [comment]
I was able to loot it on my alliance character rather quickly, but still have not been able to get it on my horde character.  Is this something that could be the problem?

**Comment by Nzzoth** [comment]
Hello goody9302, I doubt that is the case as loottables are bound to NPCs and have nothing to do with your faction, you were probably unlucky. However I can be wrong, for now this will be threated as the problem has been resolved until we get more reports that support what you mentioned.

Kind regards, Nzzoth.

**Comment by Kaiitothewai** [comment]
@goody9302 - Its very possible that there is a faction issue with the drop, it's been seen many times
