### ISSUE TITLE
[Quest] Mantles of the Dawn

### ISSUE THREAD

**Issue by redmagejoe** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4796]
http://database.wow-one.com/index.php?quest=5504
http://database.wow-one.com/index.php?quest=5507
http://database.wow-one.com/index.php?quest=5513

These three quests are supposed to be linked, and completing one of them should close the others at other NPCs. Currently, you can do all three of them for experience or money, though as soon as you complete the first. I am not sure if you should be able to turn the quest in to any NPC, or only the NPC you started the quest from. I would assume with the unique quest IDs it is the latter.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**

**Comment by redmagejoe** [comment]
I'd like to make an addendum to this issue: The Mantles, both the regular ones (at Honored) and the Chromatic ones (at Exalted) immediately appear in the wares of the Quartermasters as soon as you achieve the necessary reputation. These quests as well as the Chromatic Mantles quest are supposed to be required to ACCESS the mantles in the first place.
