### ISSUE TITLE
[Quest] Armor kits for the field

### ISSUE THREAD

**Issue by Raca91** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4799]
http://v.youku.com/v_show/id_XODM4NzQ5NjE2.html?qq-pf-to=pcqq.temporaryc2c

Here is a video that demonstrates it. The problem is as you can see that I have all the logistics task briefing 1-xi but the last reward is empty. This quest works fine for most people, but not me (Muteclaw).

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
