### ISSUE TITLE
[Windstone Bosses - Silithus]

### ISSUE THREAD

**Issue by Usernameisalreadytakenisalreadytaken** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4802]
All twilight bosses should yield reputation after the following scheme: lesser Windstone boss: 5 rep, normal Windstone boss 25and higher 50.

Desired state: Rep

Current State: No Rep :<

Sources:
http://www.wow-one.com/forum/topic/86014-cenarion-reputation/page__fromsearch__1

http://www.wowwiki.com/Cenarion_Circle_reputation_guide

http://www.wowwiki.com/Cenarion_Circle_reputation_guide?oldid=378482

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
