### ISSUE TITLE
Chest of Spoils from Abyssal Scepters dont drop money, as it should.

### ISSUE THREAD

**Issue by Usernameisalreadytakenisalreadytaken** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4803]
The reward for giving in Abyssal Scepter is horribly wrong. After giving in one of the two quests to get Chest of Spoils it offers no blue or green items (which seems might have been bad luck on my side) and no money after several tries.

Sources: Just every comment on the bigger sides regarding Chest of Spoils.
http://www.wowhead.com/item=20602

Additional: My sample is small, but it hints that it might be low on buffmats as well. Every screenshot/lists contains 2-3 (parts of a) stacks, while I only received one. Don't have enough of proof for that one though.

Current state: Chest of Spoils misses vital part of the reward.

Desired state: Random value between 60g and 100g.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
