### ISSUE TITLE
Rogue Nightslayer Armor 8/8 piece bonus not working.

### ISSUE THREAD

**Issue by Hegelol** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4815]
No matter what I do, the Nightslayer 8/8 bonus:

"Set: Heals the rogue for 500 when Vanish is performed." 

is not working. I have cleared my cache and WTF folder and tried it on different computers, Vanish never healed me. 

Thank you

**Comment by Hegelol** [comment]
A month later there are no signs anyone acknowledged the problem.

Any hopes that the Nightslayer 8/8 bonus could get fixed?

**Comment by Nzzoth** [comment]
Hello Hegelol, this is not a public forum we don't discuss issues here and to answer your question the issue did not go unseen.

**Comment by Hegelol** [comment]
Thanks, since it's my first post here I just wanted to check if I'm missing anything or if I correctly posted the issue

**Comment by Kaiitothewai** [comment]
http://www.wow-one.com/forum/topic/46099-tier-set-bonus-testing/
