### ISSUE TITLE
[CLASS] [WARLOCK] Lesser Invisibility - Succubus spell should not be able to recast it once in combat

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4836]
Lesser Invisibility
100 mana
Instant
Gives the Succubus Lesser Invisibility for up to 5 min. This spell can only be used out of combat.

http://db.vanillagaming.org/?spell=7870

I can't believe no one has reported this bug before - it makes Succubus so frickin annoying as Warlocks are able to just spam Seduction ad nauseum and then cast shadow bolts at will - since the Succubus turns invisible and breaks target selection once the seduction ends.

The player's ability to right-click this spell only means that it will automatically recast Invisibility on the succubus once the Warlock leaves combat, not upon Seduction ending via dmg to the opposing player or the 15 second cd finishing.

Just like a hunter's pet or a Kitty Druid cannot re-enter Prowl if they remain in combat.

Here is the most recent version of the spell which shows the Auto-Cast toggle as well:

Succubus: Lesser Invisibility	Passive
Requires Warlock
Requires level 33
Grants your Succubus the ability to cast Lesser Invisibility.

Lesser Invisibility	Special Ability
20 Energy
Instant
Gives the Succubus Lesser Invisibility for up to 5 min.  This spell can only be used out of combat.

Auto-Cast:
Reapply when the Succubus leaves combat.

(Right - Click to toggle)

http://www.wowhead.com/spell=103140

The problem actually lies in Seduce - it's not causing either the Warlock or the Succubus to enter combat when it's used on an opposing player:

https://www.youtube.com/watch?v=mSRlkyhoL-I&feature=youtu.be
#4640

**Comment by Akensai** [comment]
Has this been forgotten about?

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
