### ISSUE TITLE
Alterac Mountains Quest - Ensorcelled Parchment - Alliance

### ISSUE THREAD

**Issue by goody9302** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4841]
When you are on the quest, Dark Council, to kill Nagaz and 4 shadow mages in the house in northern Alterac Mountains, there is a chest inside called Worn Wooden Chest.  Inside this chest, there is supposed to be an item that starts another short quest line beginning with the quest, Ensorcelled Parchment.

http://www.wowwiki.com/Ensorcelled_Parchment
http://db.vanillagaming.org/?quest=551#wh-comments
http://www.wowhead.com/quest=551/deprecated-the-ensorcelled-parchment

After this quest, there is another quest called "Stormpike's Deciphering."

http://www.wowwiki.com/Quest:Stormpike%27s_Deciphering
http://db.vanillagaming.org/?quest=554#wh-comments
http://www.wowhead.com/quest=554/deprecated-stormpikes-deciphering

I just wanted to point these things out as not working because currently inside that chest in the house, the quest item is not there.  I have tried looting it several times but nothing happens.  Perhaps it is a low drop rate but even so, I have looted it over a hundred times and no quest item.  Perhaps someone could look into this.  Thanks.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
