### ISSUE TITLE
[Item] Riding turtle tooltip

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4845]
Riding turtle (ID:23720) appears as a bag in the tooltip and it should be a mount.
http://i.imgur.com/KkEbsWU.jpg

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Cabro** [comment]
This is actually live. :)

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
