### ISSUE TITLE
[Quest][Seasonal] ~ Smookywood Pastures Gift Pack

### ISSUE THREAD

**Issue by Mofoleone** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4853]
http://database.wow-one.com/index.php?item=17727

Tends to be empty!

![](http://i.imgur.com/tn8zb4g.jpg)

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
