### ISSUE TITLE
warrior spell: Intercept

### ISSUE THREAD

**Issue by Chulain** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4860]
warrior spell "intercept" doesn't crit

i wouldn't know why it shouldn't crit, it's physical damage

why is this so important? a crit could activate other abilities/talents: Deep Wounds, Flurry, etc

**Comment by Salce** [comment]
https://www.youtube.com/watch?v=FrnzhjNtPrg&feature=youtu.be&t=1m13s

Uses Reck > Uses Intercept > No Cirt (You can see theres no deep wounds until the auto attack crits.

If you find any evidence suggesting otherwise please feel free to post it here until then I will close this report.
