### ISSUE TITLE
D2 warrior quest line broken?

### ISSUE THREAD

**Issue by bucknaked** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4865]
I have completed all the quests. I did alcaz island and everything already. It isnt offering me the final turn in quest to get my head and chest of heroism. Character is Bucknekkid on Warsong server. level 60 undead warrior.

**Comment by Kaiitothewai** [comment]
Report back if still a issue.

**Comment by bucknaked** [comment]
I don't know what fixed it exactly but I was able to do additional quests
and get all the pieces. Thanks

**Comment by Kaiitothewai** [comment]
That's good and thank you for reporting back
