### ISSUE TITLE
[Quest][Tanaris] Seeing What Happens - Wrong Level Requirement

### ISSUE THREAD

**Issue by rsheep** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4879]
http://database.wow-one.com/index.php?quest=2946
This quest cannot be accepted at lvl 47. Level 48 is needed.

It's marked "level 45" even on your DB.

https://web.archive.org/web/20060527174304/http://wow.allakhazam.com/db/quest.html?wquest=2946
http://www.wowhead.com/quest=2946
https://web.archive.org/web/20070709051104/http://www.thottbot.com/q2946
http://www.wowwiki.com/Quest:Seeing_What_Happens_%28Alliance%29
http://old.wowdata.ru/quest.html?id=2946

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Goanno** [comment]
Fix confirmed on PTR.

**Comment by Kaiitothewai** [comment]
**Live with Patch 10.10**
