### ISSUE TITLE
Duel forfeit animation missing.

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4884]
After you forfeit a duel you don't bow down and beg for mercy but you're unable to move for 2 second just like you wouldn't be able if the animation was being done.

Note that you bow down and beg for mercy after you lose a duel and the animation is properly done and you can't move while you're doing the animation until the end of it.

**Comment by Akensai** [comment]
I would like to add to this (because I'm lazy) that when the duel flag up Blood Rage (Warrior) lasts the full duration even if cancelled. This only happens when a duel flag is up and is quite well known to warriors (eg, cancelling duel to battle shout with blood rage before re dueling).

**Comment by Nzzoth** [comment]
**The issue has been fixed**
Closed.
