### ISSUE TITLE
Rhapsody's Tale (Quest in The Hinterlands)

### ISSUE THREAD

**Issue by Hairypooter** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4887]
When handing in the quest Rhapsody's Kalimdor Kocktail, the dialogue which is supposed to lead to the next quest, (Rhapsody's Tale) doesn't finish. This stops you from getting the new quest. Please fix it ASAP along with other quests! ^-^

**Comment by Nzzoth** [comment]
Please do not close issues on your own.

**Comment by Nzzoth** [comment]
#2899
