### ISSUE TITLE
Kurinaxx's Sand Trap script is not enabled

### ISSUE THREAD

**Issue by ender-feenix** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4890]
Placeholder issue to track overlooked fix.

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by ender-feenix** [comment]
Supposedly overlooked fix was in fact redundant.  Closed.

**Comment by Cabro** [comment]
You are on the right track. Sand traps are semi scripted, in the way that:
- they are instant or 1s detonated (on every video from that time you will see you have like 3-5s after they appear to move away before they detonate).
- missing detonate animation.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PLTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
