### ISSUE TITLE
Rogue: Serrated Blades bug (not ignoring enemy armor)

### ISSUE THREAD

**Issue by hawai** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4897]
Currently talents Serrated Blades dont add +ignore armor to your attacks. @ 3/3 all attacks should ignore 8 of enemy armor.
Fix that pls.

**Comment by hawai** [comment]
also gouge breakin randomly like after 2-3 sec instead of 5. Sap beeing broken by enchants (lifestealin).

**Comment by hawai** [comment]
rogues beein useless in pvp not even most. thx.

**Comment by Kaiitothewai** [comment]
What makes you believe Serrated Blades do not ignore armor?

**Comment by hawai** [comment]
well when you look at tooltip in the talents. It says it just adds 30%to rupture but says it adds 0 ignore armor.

**Comment by hawai** [comment]
it should add
1/3 2.67 ignore armor
2/3 5.34 ignore armor
3/3 8 ignore armor

**Comment by hawai** [comment]
also why is Gouge broken and randomly breaks after 1or2or3 seconds?

**Comment by Kaiitothewai** [comment]
That's just a Tooltip error, did you actually test it? This has reported many times before.

**Comment by ender-feenix** [comment]
Gouge does not break randomly every few seconds according to our tests.  I imagine you are falling victim to diminishing returns.  The issue of it breaking due to proc damage has been fixed.

**Comment by Kaiitothewai** [comment]
#1837
