### ISSUE TITLE
Rogue: Gouge breaking randomly.

### ISSUE THREAD

**Issue by hawai** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4898]
Gouge ability after some of latest patch is now breaking completly randomly. Tested it in duels and in WSG as well. Sometimes it breaks after 1or2or3 seconds. 
Also I witnessed that it has been broke by lifesteal proc (is it rly blizzlike like that?) Not talking about Sap as Ive read you think its blizzlike like this.

**Comment by ender-feenix** [comment]
We actually fixed Sap so that a damaging proc triggered by Sap will not cause the Sap to break.  If I read this correctly, you're saying that the same behavior should be applied to Gouge?

**Comment by hawai** [comment]
well yes. But thing is gouge is breaking completly randomly even without damagin opponent after like 1or2or3 seconds.

**Comment by Nzzoth** [comment]
Issue tested on Warsong.
Gauge doesn't randomly break. It's always 4 seconds on first cast.
Procs from instant poison and weapons do break gauge.(Needs to be fixed)
