### ISSUE TITLE
[Script] High Priest Thekal

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4899]
Currently on Live and PLTR the fight is broken.

Killing any of the 2 the Zealoths or Thekal himself does not trigger the timer for ressurection (they should resurrect whenever 1 of them is still alive after a few seconds)

Killing them within the required time will not trigger Thekal to resurrect and transform into a tiger. They will simply lay there (untargettable) and keep you in combat.

If you happen to kill Thekal first, it appears the link for adds breaks. You can kite them out of the room as far as you like. However kiting them out of the room will cause Thekal and, if killed, the other Zealot to respawn. Once full reset the third Zealot, which you have kited away and killed does not respawn.

http://www.wow-one.com/forum/topic/91250-thekal-issue-012015/

**Comment by Akensai** [comment]
Just noting that we did this Sunday morning and I experienced similar with 1 exception.

Fight went as normal until AOE on the 3 of them, both adds died at the same time and Thekal died within 2 seconds of them both being dead. He did not resurrect in tiger form but instead stayed dead and dropped loot.

**Comment by ender-feenix** [comment]
A fix for this has been submitted.

**Comment by ender-feenix** [comment]
The fix for this went live yesterday with patch 10.3.1.
