### ISSUE TITLE
Hunter & Warlock pets dont have hearbeat mechanic

### ISSUE THREAD

**Issue by lequintal69** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4907]
Pets will get FULL duration cc's (30 secondes sheep, 20 sec fear) which is not blizzlike.

**Comment by griesakanik** [comment]
Can you provide proof of your claim?

**Comment by Akensai** [comment]
This can be reproduced by:
Create level 60 hunter
Any pet at any level
Create level 60 mage
Duel hunter and sheep pet

Sheep lasts entire duration (no heartbeat)

**Comment by Kaiitothewai** [comment]
Could somebody try and find a video of this please? :)

**Comment by Akensai** [comment]
It's quite hard to find a video since in retail hunters raped most things that would CC a pet before they could cast CC (let's get these bugs fixed!).

I do remember it as @lequintal69 explains in vanilla. For what it's worth.

**Comment by Nzzoth** [comment]
https://www.youtube.com/watch?v=RNfh6jUIPqA&index=3&list=FLgVgu4XCzvz9eJZqv0Dr7dg
8:11
9:52

**Comment by Kaiitothewai** [comment]
Thanks

**Comment by Nothhelm** [comment]
That pet was clearly hit with multishot in that video.

**Comment by griesakanik** [comment]
at 8:11 yes but if you watch the whole movie it's working like op described

**Comment by lequintal69** [comment]
https://www.youtube.com/watch?v=v5bIKjadBfw

at 8:10 the warlock fears the wolf. At 8:17 the wolf is already coming back

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
