### ISSUE TITLE
[Rogue] Bonescythe 8 set bonus not working

### ISSUE THREAD

**Issue by ninjacorpse** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4909]
Hi,

I noticed all topics regarding this is closed/broken links so I am reopening this.

The rogue t3 8/9 set bonus:
Revealed Flaw
Instant.
Your Eviscerate has a 20% chance per combo point to reveal a flaw in your opponent's armor, granting a 100% critical hit chance for your next Backstab, Sinister Strike, or Hemorrhage.

http://database.wow-one.com/?spell=28814

This spell trigger:

http://database.wow-one.com/?spell=28815

Revealed Flaw Instant.
Increases the critical strike chance of your next Sinister Strike, Backstab, or Hemorrhage by 100%.

Glow appears on Main hand (right hand) shares same visual effect as cold blood
Screenshot added from 2008/10/08
http://www.wowhead.com/spell=28814/revealed-flaw#screenshots

Currently it does nothing at all with 1, 2, 3, 4 or 5 combopoints for over a year now.

**Comment by ender-feenix** [comment]
https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/4754#issuecomment-70048184
