### ISSUE TITLE
[Hunter] Set bonus's effecting pets break Cast Bar.

### ISSUE THREAD

**Issue by Akensai** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4913]
Opening new issue regarding this as the cause has been found:
https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/4874

Set bonuses that give a buff to pet cause cast bar to not work when the pet is not out.

To reproduce
Create level 60 hunter
Loot full Tier 2 (Dragonstalker)
Call pet
Dismiss pet
Cast anything

**Comment by Kaiitothewai** [comment]
#2463

**Comment by Kaiitothewai** [comment]
Use the other one

**Comment by Akensai** [comment]
The other one has been necro'd for over a year. Why necro it again?

**Comment by Kaiitothewai** [comment]
Why would you make a duplicate just because it's a old report (?)
