### ISSUE TITLE
Bugged Pet Immune to Crowd Control

### ISSUE THREAD

**Issue by Akensai** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4914]
This has been known for awhile now but now the entire server (Warsong) is using the pet. As such it doesn't make much difference if I publicly say the name.

Level 27 tamable rare bat named Blind Hunter inside Razorfen Kraul is immune to all CC/Snare effects. This includes curses, magic, poison, and physical effects.

The mob needs to be fixed or removed as soon as possible. About half of all hunters are using it in PvP as of today (Warsong).

**Comment by ender-feenix** [comment]
A fix for this issue has been submitted.  Note to future readers: the author of this issue giving it a name that starts with "[Priority]" has no bearing on where we choose to focus our efforts.  Please do not start naming everything like that!

**Comment by Kaiitothewai** [comment]
**Fix is Denied on PTR**

**Comment by Akensai** [comment]
So, shall we go ahead and start reporting abuse for those using it since it seems the fix is a bit off?

**Comment by Nzzoth** [comment]
You are always free to report somebody on Feenix forums if you believe they're doing something against Feenix rules. We the testing and developing team do not deal with this.

**Comment by ender-feenix** [comment]
This was re-fixed and went live yesterday.
