### ISSUE TITLE
Mailbox.

### ISSUE THREAD

**Issue by beanburritomanx** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4922]
Censored.
http://www.wow-one.com/forum/topic/91830-mailbox/

**Comment by fitsroyal** [comment]
This is out of control right now btw and I don't know why there's not a response to it. It was reported here too http://www.projectfeenix.com/forum/topic/91587-quest-item-abuse-for-gold-112/. And I think this was reported even as far back as august (On the forums but still something of this magnitude of abuse shouldn't be taken lightly.)

**Comment by fitsroyal** [comment]
Why was my comment deleted? This is seriously out of control right now

**Comment by ender-feenix** [comment]
Because it did not contribute any information to the topic.  A fix for this has been applied.
