### ISSUE TITLE
[Priest] Inner Fire charges should not be consumed on fully absorb physical damage.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4936]
It was working correctly until a few patches ago when you made everything proc on absorb.
This was an exception.

On retail Inner Fire charges were not consumed on full absorb physical damage.

**Comment by Nzzoth** [comment]
Please provide a source to support your report.

**Comment by Rulerx** [comment]
who is the bad guy now Cabro

**Comment by Nzzoth** [comment]
Need a remind you that this is not a forum. Only comment if you're providing useful feedback regarding the issue at hand.

**Comment by Cabro** [comment]
Yea i'll find a movie at some point. Busy doing something else atm, but keep this bug report opened.

**Comment by Cabro** [comment]
http://www.wowwiki.com/Patch_1.10.2
Inner Fire: Rank 3 will no longer have charges consumed when Power Word: Shield is active.

Apparently this rank was the only one that was still behaving like it is now on Feenix, and it was a BUG. Which had been fixed in patch 1.10.2.

**Comment by Nzzoth** [comment]
Hello Cabro, thanks for you feedback we will further discussion about this issue will be held here #4971

Kind regards, Nzzoth.
