### ISSUE TITLE
[Warrior] Bloodrage can not be removed with Duel Flag.

### ISSUE THREAD

**Issue by Akensai** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4937]
Title says it all.

Bloodrage can not be removed when a duel flag is up. You remain in combat the full duration even after the buff is removed. This is not game-breaking, but it is very annoying for warrior's to duel. An annoyance mostly.

Reproduce
Level 60 warrior
/duel anyone (without accepting duel)
Use Bloodrage
Remove Bloodrage
Remain in combat full duration.

**Comment by Kaiitothewai** [comment]
#4795
