### ISSUE TITLE
[QUEST] Warlock (Horde) quest "Devourer of Souls" to get succubus

### ISSUE THREAD

**Issue by nerfologist** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4939]
Hello,
as a Horde undead warlock I correctly got the [Devourer of Souls quest](http://db.vanillagaming.org/?quest=1472) from [Carendin Halgar](http://db.vanillagaming.org/?npc=5675) in UC al level 20.

Later, having the quest log full, I abandoned it, knowing that I could pick it up on my next visit to the class trainer in the area.

Unfortunately, on visiting [Carendin Halgar](http://db.vanillagaming.org/?npc=5675) again, the quest is nowhere to be found.

Can you fix it?

Thanks in advance! :smile:

**Comment by nerfologist** [comment]
Update: tried to get the [other quest from Orgrimmar](http://db.vanillagaming.org/?quest=1507) at [Gan'rul Bloodeye](http://db.vanillagaming.org/?npc=5875). He had nothing to give me, so I guess there's no other way to obtain the Succubus.

**Comment by nerfologist** [comment]
Can the flag for obtaining the quest be reset manually? I have no other way to obtain the Succubus pet on my warlock. Char: **Ende**, undead warlock. This is a serious impairment for a lock.

**Comment by Nzzoth** [comment]
Greetings,

Make an ingame ticket for support with the quest.

Kind regards, Nzzoth.

**Comment by devidao** [comment]
Can not reproduce on PTR, working fine.

**Comment by Nzzoth** [comment]
Tried to reproduce on PLTR and WSG, it appears that this is a isolated case.
If you could provide us with additional evidence to support your issue or a complete reproduction guide I'll gladly reopen the issue until then closed.

Kind regards, Nzzoth.

**Comment by nerfologist** [comment]
Thanks for taking the time to investigate this.

Just to provide an extra bit of info, I experienced this problem as an Undead Warlock on Emerald Dream.
