### ISSUE TITLE
Blood Fury adding +25% AP to all AP instead of Base.

### ISSUE THREAD

**Issue by Akensai** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4944]
Opening a new issue for this as it was resolved and then broken again
https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/2177

Blood Fury is supposed to add +25% to base AP on Orcs. However, it is adding +25% to all AP on the player.

Currently:
Orc Rogue with 1000 total Attack Power
Use Blood Fury
Orc Rogue now has 1250 Attack Power.

Should be:
Orc Rogue with 1000 Attack Power
Use Blood Fury
Orc Rogue now has 1077 Attack Power (310 base + 25% = 77.5 Attack Power)

I noticed that it was possible for my Warrior as Orc to get 1950 Attack Power with no buffs except for Battle Shout. And nearly 3k Attack Power with raid buffs. This is entirely game breaking to PvP and PvE due to the massive amount of attack power that can be gained.

In Warrior's case I had 2291 Attack Power with raid buffs/consumables, 2291+25% = 2863 Attack Power. I then entered WSG and Mortal Strike'd a Mage for 4.1k damage. Then just to really see a big number I went and grabbed Berserker Buff (WSG) and nearly deleted a T3 priest (5.4k Heroic Strike).

This was resolved once already but the issue has come back. Needs to be fixed again.

**Comment by Nzzoth** [comment]
Hello Akensai, the following issue you posted is a duplicate as the issue  #2177  was not resolved.

Issue closed.
