### ISSUE TITLE
[Rogue][Sap applies poison]

### ISSUE THREAD

**Issue by Mofoleone** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4947]
When you use sap and have crippling poison on weapons, it is applied to the target.

**Comment by Nzzoth** [comment]
Hello Mofoleone, this is not a bug but a blizzlike feature we recently added in patch 10.2 which you can read on our forums www.wow-one.com .
Issue closed as it is not a bug.

**Comment by FeenixDrakon** [comment]
As a retail rogue during Vanilla/TBC, I can confirm that Sap did NOT apply poisons!
