### ISSUE TITLE
Warlock can not cast spells

### ISSUE THREAD

**Issue by angiegao** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4948]
I contacted GM online several days before. 
As his opinion, I reinstall my client, But i still have the same trouble..

I can use instant spells, But my casting always BE AUTOMATICALLY STOPPED, such as 'Rain of Fire''Ritual of Summoning''Hellfire', even fishing!! That means I can't use all of the spells which need time to cast..

It is very strange that sometimes I can use thoese spells very well, but most of the time I can't. 
E.g., I can use 'hellfire' in IronForge. Then i go through the portal to Stormwind, I CAN'T use it  
QAQ

My friends also tried to use my warlock, but they have the same issue as me. Btw, my other priest and mage works very well. The problem occurs Only in the warlock!! So, I think the problem is not my client...Perhapes there is something wrong with the data of My warlock.
Could you help me to check it?

I really need help..QAQ　A warlock cant summon others that troubles me alot..
I am greatful to u for helping.

**Mod account information removed-Nzzoth**

**Comment by Kaiitothewai** [comment]
T1 or T2 5 Set Bonus most likely.
