### ISSUE TITLE
[Warrior] Bloodrage delays exiting combat.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4949]
If you use Bloodrage while you are in combat with anything (NPC/Player), you will exit combat with 10s delay.

Kinda gamebreaking in PvP when you can't mount up.
Consequently, if you buff/heal a warrior that has used Bloodrage in combat, you will also leave combat 10s later than properly.

**Comment by Nzzoth** [comment]
#4795
