### ISSUE TITLE
[CORE][Battleground entering in combat]

### ISSUE THREAD

**Issue by Mofoleone** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4967]
Current state:
You can enter battleground in combat.

Desired state:
You cannot enter battleground in combat.

**Comment by Nzzoth** [comment]
Greetings,

Can you provide evidence of this being the case in 1.12?

Kind regards, Nzzoth.

**Comment by Mofoleone** [comment]
Greetings, 
I don't want to sound rude or anything but your response is hilarious.

Anyone who ever did any sort  of PVP knows this, it's the same on every expansion, and it worked properly on warsong pre core merge.
Hint: That's how people kept PVP high rankers outside of premades by keeping them in combat and not allowing them to join.

Evidence, don't be silly.

Kind regards, Mofo

**Comment by Cabro** [comment]
http://www.ticopa.com/wowbg/topics/generalrules.html for example

**Comment by Nzzoth** [comment]
Hello Mofoleone, I had reasons why I asked the question even though the question to you as you stated is hilarious.

Thank you Cabro.
Kind regards, Nzzoth.

**Comment by Forcy** [comment]
I decide if this is an issue or not.

**Comment by Mofoleone** [comment]
Do you even blizzlike?

**Comment by Mofoleone** [comment]
Are you for real @Forcy

**Comment by Mofoleone** [comment]
You want bug report, you got it and now you're going "I AM THE LAW" here because you either don't approve real issue here? Hi-larious.

**Comment by ender-feenix** [comment]
I think his dictatorial tone was intended as a joke.  But in all honesty we cannot fix this until we fix the issues that cause people to be stuck in combat when they shouldn't be.  Not to mention there is potential for trolling here, etc. and it's just not that big of an issue.

**Comment by Mofoleone** [comment]
Compare it to ALT F4 in combat during boss event in raid instance, where people logout to either reset aggro/preserve buffs, same thing is done in PVP and that really matters for PVP players, especially in world PVP, in past few weeks when people again started to be more active in certain high level zones.

Back on warsong, two years ago (pre core merge), one way of "sabotaging" premades was to keep leader or few members of that premade in combat, during the "invite for battleground". Those things are missing, and it gets frustrating when you try to "world pvp" against some players, let's say in silithus and on 10% HP they get away by joining battleground.

It is a big deal for PVP players, and it should be connected with bug where people could ALT F4 in combat to abuse PVE mechanics too.
People were doing that on ED(horde especially) to abuse "aggro reset" on warlocks, I know some of them even got banned year ago, but now nobody cares.

It is a legit bug and should be treated like one, I don't see how that is not a big deal here.
There you go.

Delete report or whatever, this is a legit bug report, just this kind of attitude from Forcy is really out of line, and we all know not many people even bother to visit bugtracker to report bugs, and when they see "this", this doesn't give proper picture of feenix to anyone.

**Comment by ender-feenix** [comment]
I'm sorry you disagree with our opinion on it.  But that is all it is.  Don't read more into it than that, please.  Your melodramatic response is transparent, predictable and a perfect example of why (speaking for myself here) it is so headache-inducing to engage in these kinds of conversations.

That being said, though I don't talk much, we do always listen.  And I think we can both agree that there are more important issues than this right now -- you even mentioned some of them.

We don't delete any reports, but it will remain closed for now.  I have applied the WontFix label so it will show up in a later review.  I have also locked this issue as all relevant information for this issue has been presented.
