### ISSUE TITLE
[Item] Enamored Water Spirit

### ISSUE THREAD

**Issue by Cwasm** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4968]
Enamored Water Spirit (http://www.wow-one.com/database/index.php?item=20503) is a Shaman quest Reward from "Da Voodoo" (http://www.wow-one.com/database/index.php?quest=8413) and according to it's tooltip is supposed to return 27 mana every 2 seconds, it's only returning 10 every 2 seconds making this item nowhere near as powerful as it should be.
![manabug1](https://cloud.githubusercontent.com/assets/10804790/5996008/a57ac5f8-aa54-11e4-8e26-abc1cf0d04f9.png)
![manabug2](https://cloud.githubusercontent.com/assets/10804790/5996011/af73bd08-aa54-11e4-94b1-7fb287d311d2.png)

**Comment by Kaiitothewai** [comment]
#2304
