### ISSUE TITLE
[BG] Losing team should not get Mark.

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4970]
Patch 1.8.4 (05-Dec-2005): Battles must now last at least ten minutes after the start of the battle in order for the losing team to receive a Mark of Honor.

http://www.wowwiki.com/Battleground
#4969

**Comment by TomGhb** [comment]
The above change was never meant to be implemented on live servers, and was quickly hotfixed after it mistakenly made it into the patch notes. 

For details see http://www.gosugamers.net/dota2/news/3538-us-wow-1-8-4-released-details
