### ISSUE TITLE
[Priest] Inner Fire charges should not be consumed on fully absorb physical damage.

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4971]
It was working correctly until a few patches ago when you made everything proc on absorb.
This was an exception.

On retail Inner Fire charges were not consumed on full absorb physical damage.
http://www.wowwiki.com/Patch_1.10.2
Inner Fire: Rank 3 will no longer have charges consumed when Power Word: Shield is active.

Apparently this rank was the only one that was still behaving like it is now on Feenix, and it was a BUG. Which had been fixed in patch 1.10.2.
#4936

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
