### ISSUE TITLE
Quest: Long Forgotten Memories & A Pawn on the Eternal Board

### ISSUE THREAD

**Issue by xefury** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4972]
I heard these 2 quests got fixed and decided to give it another ago.

I completed Long Forgotten Memories a long time ago and abandoned the next part because the quest was disabled. Now, when I try and re obtain the quest, I can no longer get it. I tried clicking on the crystal and talking to Anachronos, but I can never get the quest. Is there a way to pick up the quest so I can complete A Pawn on the Eternal Board?

**Comment by Kaiitothewai** [comment]
Its disabled on Warsong and Al'Akir, just wait for the quests to get fixed on there.

**Comment by headlong93** [comment]
Still not working
