### ISSUE TITLE
Arena Grand Master q bug

### ISSUE THREAD

**Issue by Buxna** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4973]
Ok so, today after getting my 9th Arena Master  for some reason I went and handled the "Arena Master" q in at the mob. I went for next chest and I couldn't see Arena Master trinket inside the chest loot table. Searched the forums and found it it's a bug. http://www.wowwiki.com/Arena_Grand_Master , I got some screenshots too, http://imgur.com/PPUXszf,Iwp3CsA,06Oq9cZ.

**Comment by Kaiitothewai** [comment]
#2031
