### ISSUE TITLE
[Item] Iceblade Hacker frost damage missing

### ISSUE THREAD

**Issue by inkwiz** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4990]
The Mainhand axe [Iceblade Hacker] dropped by Ras Frostwhisper, Scholomance does not cause any bonus frost damage.

http://db.vanillagaming.org/?item=13952

Tested on Durotar boars and various Azshara and Winterspring mobs 3.2.2015; Emerald Dream.

**Comment by Cabro** [comment]
The whole elemental damage system is missing. It's not only this weapon.

**Comment by Kaiitothewai** [comment]
#4992
