### ISSUE TITLE
Chat Mute

### ISSUE THREAD

**Issue by Bigepo** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#50]
Can you turn off the chatmute after writing 4or 5 lines.
In, Guildchat, Raidchat, party, officer, etc.. It's realy realy realy annoying
And when GDKP's start running its annoying getting muted after linking item and countdown...

Cheers

**Comment by anaaz** [comment]
That's not going to happen.

**Comment by Bigepo** [comment]
Cant you only mute worle and public channs?

**Comment by Bigepo** [comment]
World *

**Comment by anaaz** [comment]
Spam filters are there for a reason, doesn't matter if it's public or private chat
