### ISSUE TITLE
[BRD] Mobs that should flee when low on HP.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5013]
https://www.youtube.com/watch?v=J-aeXRGhReU
https://www.youtube.com/watch?v=GR_CQ-eC6ns

Anvilrage Medic npc=8894
Anvilrage Overseer npc=8889
Anvilrage Guardsman npc=8891
Anvilrage Footman npc=8892
Anvilrage Warden npc=8890
Twilight's Hammer Torturer npc=8912
Houndmaster Grebmar npc=9319
Doomforge Dragoon npc=8899
Anvilrage Marshal npc=8898
Weapon Technician npc=8920
Shadowforge Citizen npc=8902
Doomforge Arcanasmith npc=8900
Shadowforge Senator npc=8904
Twilight's Hammer Ambassador npc=8915
Anvilrage Captain npc=8903

**Comment by Akensai** [comment]
Most mobs in BRD as of now due actually flee, even those that aren't supposed to. The "Runs away" message is not shown and the flee is kinda funky, mobs just untarget and run in a circle. Something seems to have been broken recently with it.
