### ISSUE TITLE
[CORE][Battleground entering in combat]

### ISSUE THREAD

**Issue by Mofoleone** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5027]
Current state:
You can enter battleground in combat.

Desired state:
You cannot enter battleground in combat.

Proof
http://www.ticopa.com/wowbg/topics/generalrules.html

**Comment by Nzzoth** [comment]
Greetings,

You were given an asnwer regarding this issue in #4967 .

Kind regards, Nzzoth.
