### ISSUE TITLE
[BRD] Grom Patron issues.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5067]
npc=9545

1 - it is missing ability Kick (15610) - http://web.archive.org/web/20100424193719/http://www.wowhead.com/npc=9545
2 - if Plugger Spazzring is killed, it should:
2.a - do a /roar animation, but without the emote text.
2.b - become hostile.

@Nzzoth don't close this, need to do emotes research.

**Comment by wlfbck** [comment]
https://www.youtube.com/watch?v=3mIkmIdpEW4&feature=player_detailpage#t=194

**Comment by wlfbck** [comment]
They do nothing when Plugger is killed btw.
https://www.youtube.com/watch?feature=player_detailpage&v=8fcIOPlCNFM#t=177

**Comment by Nzzoth** [comment]
Greetings,

Any further discussion regarding this issue will be held in issue #5072
Issue closed.

Kind regards, Nzzoth.
