### ISSUE TITLE
Lost my character

### ISSUE THREAD

**Issue by noobkilla625** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5069]
Haven't played vanilla wow since before the ED merger... now when i log in i have no characters showing. I tried entering my old characters name as a new character and it says it is unavailable so i know he's out there somewhere! Any help on how i can get him back?

**Comment by Nzzoth** [comment]
Greetings,

This is not a place where we handle such issues for further assistance with your account make a topic here: http://www.wow-one.com/forum/72-account-issues/ .

Kind regards, Nzzoth.
