### ISSUE TITLE
[BRD] Hurley Blackbreath + his guards issues.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5081]
Hurley Blackbreath npc=9537
Blackbreath Crony npc=9541
https://www.youtube.com/watch?v=NsD9eEKWo0o (exact same script since BRD was released, but higher quality)

1 - After you destroy the 3rd Keg from #5082, Hurley and 3x Crony should spawn at the top of the stairs that lead to the bar (Grim Guzzler).
2 - all 4 NPCs should be flagged as hostile, targettable but unattackable.
3 - upon spawn, Hurley should yell: "Hurley Blackbreath yells: Get away from those kegs!"
4 - they should run into the room with the barrels, stopping after 4-5 yards from door (we need this so we don't aggro adds from outside the door, making this fight harder than it should be).
5 - the 3x Crony should stop a bit behind Hurley, to make it easier to target the NPCs. (especially with how NPCs stack up on top of each other on Feenix).
6 - they should become attackable at this point.
7 - upon engage, Hurley should say: "Hurley Blackbreath says: You'll pay for that!" (end of correct script)

Existing issues:
8 - Hurley is pre-spawned in a corner. Remove it, making it only spawnable through the keg event.
9 - Hurley is not wielding his mug (read as weapon): Hurley's Tankard (item=18044) http://wow.zamimg.com/uploads/screenshots/normal/81128.jpg
10 - Hurley is not using any abilities. It should use Flame Breath (9573) and Drunken Rage (14872) - http://web.archive.org/web/20100421015930/http://www.wowhead.com/npc=9537
11 - since i cannot test the guards (because there is no way to spawn them) it should be checked that they wield Howling Blade (item=6331) http://wow.zamimg.com/uploads/screenshots/normal/56135.jpg
12 - the crony should use Sinister Strike (15581) and Rupture (15583) http://web.archive.org/web/20100428035548/http://www.wowhead.com/npc=9541
13 - they should be linked

**Comment by Nzzoth** [comment]
#5082

**Comment by Nzzoth** [comment]
Hello Cabro, I'm still waiting for you to elaborate the issue.
