### ISSUE TITLE
[Core] If you try to use spells under MC, when the MC effect fades you cannot use anything.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5088]
Let's say you are a mage and MCed, you wanna pop Ice Block (to remove the MC). It gets stuck as pushed on bars, and when MC is over you cannot cast ANY spell until relog.

Same for priests, if you MC someone and wanna cast any spell that you know, when the MC is over, you are bugged and cannot cast ANYTHING.

Probably same with the engineering helms.

**Comment by Kaiitothewai** [comment]
That's not entirely true. You need to press ESC once or twice in order to clear it.

Annoying bug regardless. Been there since day 1.
