### ISSUE TITLE
[DMF] You shouldn't be able to have multiple DMF buffs.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5096]
#1966 related, but not fixed or addressed actually.

www.wowwiki.com/Patch_1.7.0

<code>Sayge's buffs at the Darkmoon Faire are now exclusive to one another.</code>

Right now you can get a buff, logout and wait for the 2 hours cooldown to pass, and get another buff with different stat and they will stack. You can do this until you get all the DMF buffs, when you should only be able to have 1 of them, the new one should overwrite the existing one.

**Comment by Kaiitothewai** [comment]
This was already fixed, just a missing commit
