### ISSUE TITLE
Brood of Nozdormu ring quest availability issue

### ISSUE THREAD

**Issue by Sorrugis** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5104]
After accepting the quest "Long Forgotten Memories" I went on to claim my ring but the only quest option available was "The Path of the Protector" quest for the tank ring. I have not accepted this quest as I was looking for the healing / damage / mp5 ring.

**Comment by Sorrugis** [comment]
As shown in this image, I can not view or accept the other options.

[img]http://i.imgur.com/iySb2Rw.jpg[/img]

**Comment by Nzzoth** [comment]
Greetings,

Please provide me with a screenshot with that quest open and your mouse hovering the ring it rewards.

Kind regards, Nzzoth.

**Comment by Cabro** [comment]
Nzzoth it seems it's a bug with the starting quests's for the BoN rings in terms of reputation required.

Obviously, rings that require neutral to wear should be obtained at neutral etc.

3 types of rings, and it should be checked.

Also the quests that allow you to exchange the rings are available too soon (you get them as ssoon as you reach exalted), when you should in fact get the quests after you complete the quests that reward you the exalted rings.

**Comment by Kaiitothewai** [comment]
lol

**Comment by Nzzoth** [comment]
![neutral](https://cloud.githubusercontent.com/assets/9979216/6314428/908ea3dc-b9de-11e4-90f1-38e7e0cd910c.jpg)

**Comment by Cabro** [comment]
Ups! :D

**Comment by Nzzoth** [comment]
This is most likely a player mistake, however I might be wrong as the test has been preformed on PLTR.
For now this issue is being closed.
