### ISSUE TITLE
Druid bash breaks on damage

### ISSUE THREAD

**Issue by rptb1** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5106]
The druid bear stun ability "bash" breaks on damage, including dots.

I levelled a hybrid druid in retail vanilla and I remember using bash as a lifesaving ability so that I could shift and heal myself without interruption.

I tested bash on Emerald Dream with both melee and DoT damage and both knock mobs out of stun.

Isn't it the case that *no* ability labelled "stun" in WoW should break on damage?

**Comment by Nzzoth** [comment]
Greetings,

I have tested the issue and it appears there's nothing wrong with it and it's working as it's suppose to. In case I'm wrong come back with solid evidence that supports the issue you described.

Kind regards, Nzzoth.

**Comment by Cabro** [comment]
Most likely it's breaking early because there's DR in pve for stuns. (Why is that? :P )

**Comment by rptb1** [comment]
Many thanks for your swift response!

I may be misunderstanding what's going on.  Reproduction:

1. Enter bear form
2. Enrage
3. Approach mob
4. Bash mob
5. Observe bash duration is much less than 2 seconds.

I may be wrong about it being damage that is shortening it, but it seems to be lasting around 1 second.

Video of this at https://www.youtube.com/watch?v=sHIZR87hdpU
