### ISSUE TITLE
Masterloot Issue

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5111]
When an item is masterlooted to someone in the raid, and someone in the raid becomes unelligable for the item during the loot confirmation (Leaving the raid, disconnecting, out of range) the item will go to the wrong person.

Have 5 clients open
Make any 5 characters of the same faction
Create a raid with those 5 characters
Set Looting System to Masterloot
.go c Onyxia on all 5 characters
Target Onyxia and .die
Open the loot window, chose an item and chose a character to recieve the item
While the "Are you sure .... " window is open, leave the raid/disconnect on a character that is not looting and not recieveing the loot.
The item should now go to the wrong person. Might have to retry a few times.

**Comment by Forcy** [comment]
https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/3192

**Comment by Salce** [comment]
Duplicate (Forcy pls)
