### ISSUE TITLE
[Naxxramas] Kel'thuzad is missing his enrage.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5122]
vanilla spell for his enrage: http://www.wow-one.com/database/index.php?spell=28498
wowhead link: http://www.wowhead.com/spell=28498/berserk#used-by-npc

This undeniably proves that KT should have his HP reduced, because there should be an enrage timer for this encounter.

The WotLK version for this encounter is 19 minutes from the start, so the vanilla version should be if not the same, then something like ~20 minutes.

Not having an enrage timer, and this boss having this much HP (almost 9 million) is very far from being Blizzlike. Not to mention that phase 3 is a burn phase. The burn phase having 3million+ HP is also against the design of this encounter, when the original total HP of the boss was 3.15 million (so total HP of boss was less than the feenix's burn phase HP).

HP needs adjusted, enrage needs to be added.

**Comment by ender-feenix** [comment]
The increased HP is intended.  But yes, an enrage timer should be added.
