### ISSUE TITLE
Sethir the Ancient not spawning

### ISSUE THREAD

**Issue by stonegrey** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5130]
For the Rogue [Destiny Calls] quest, can't find Sethir the Ancient. It looks like this was a problem in the past (2012 and 2013). Is he supposed to spawn elsewhere? I think I saw on a past fix for that issue that he may spawn on a hill in the area or something, but I've looked all over and can't find him. Ran into another rogue having the same problem. Waited on the branch for him to spawn, and never did.

**Comment by Nzzoth** [comment]
#1577
Closed because it's a duplicate.

Kind regards, Nzzoth.

**Comment by stonegrey** [comment]
What is the resolution? That's the previous issue that I was referencing above, and I can't find him, nor does that previous issue provide a solution. Please help.
