### ISSUE TITLE
Defender of The Timbermaw Is Still Broken

### ISSUE THREAD

**Issue by Smawl** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5135]
This exalted-required Timbermaw trinket, which has to be earned through many many hours of grinding, is still not working as of 3/1/2015.  Here is a link to the item in question: http://db.vanillagaming.org/?item=21326

Surely a dev can be assigned to script this trinket correctly so it actually heals and shoots lightning as its supposed to.  Many people have put much effort into farming the rep for it only to be dismayed upon realization that it's defective. Please.

**Comment by Nzzoth** [comment]
#1369
Duplicate closed.

Kind regards, Nzzoth.
