### ISSUE TITLE
[Quest] Glyph Chasing is bugged (Feenix)

### ISSUE THREAD

**Issue by Thalenys** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5138]
Hi,
in the last couple of days I have tried to finish the quest Glyph Chasing (http://www.wow-one.com/database/?quest=8309). When I try to loot the crystals to obtain the rubbing, it doesn't let me loot even though I have the quest and the geologist's transcription kit. After retaking the quest a couple of times, giving the quest a shot on different days at two different hives and clearing my cache I have come to the conclusion that the crystals are bugged.

Thanks for reading and I hope this can be fixed :D
Thalenys

Edit: after asking around I found out that at least two other people are having the same issue

**Comment by Kaiitothewai** [comment]
#3836
