### ISSUE TITLE
Darkshore: [12] Electropellers

### ISSUE THREAD

**Issue by kaldore** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5142]
[Project Phoenix 1.12.1 - Patch 10.0] noticed that Electropellers can now be obtained through Fishing
 but it still doesn't work 
 I couldn't get any electropellers to fish  in the cliffspring river and in the wildbend river after fishing 3 hours

**Comment by Kaiitothewai** [comment]
#483
