### ISSUE TITLE
[Quest]The Savior of Azeroth

### ISSUE THREAD

**Issue by Artzie** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5143]
Hello, I cannot complete the "Savior of Azeroth" quest from eye of c'thun to Anachronos
Current rep is unfriendly, unchecked the "at war" option, deletted WDB and still cannot talk to Anachronos

**Comment by Cabro** [comment]
I think you need at least neutral to talk to ANY NPC in this game.

**Comment by Nzzoth** [comment]
You need atleast neutral in order to talk to the NPC, issue closed.

Kind regard, Nzzoth.
