### ISSUE TITLE
[Quest] Rabine Saturna

### ISSUE THREAD

**Issue by nerfologist** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5145]
The Horde quest [Rabine Saturna](http://db.vanillagaming.org/?quest=1123) is available to players at lvl 54 instead of 55 (cannot verify if it's available to even lower levels).

Being able to pick up the quest at 54 means that, if you complete it, you are unable to pick up its followup [Wasteland](http://db.vanillagaming.org/?quest=1124) as it warns "you don't meet the requirements for this quest".

**Comment by Nzzoth** [comment]
#2894 
It's intended, issue closed.

Kind regards, Nzzoth.
