### ISSUE TITLE
Shadow Reflector reflecting magic dust

### ISSUE THREAD

**Issue by Malibuqt** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5146]
i came across a weird situation today
while in shadow form i tried to cast magic dust on enemy target who popped Shadow Reflector and the dust slept me instead.
i know for sure magic dust is not shadow spell so probably it has to do something with priest shadow form.

edit: apparently i wasnt well informed.
http://www.wowhead.com/spell=1090/sleep
school:shadow
the only bug that i could see is "arcane" glow while casting shadow school

Thanks for checking this out

**Comment by Mofoleone** [comment]
It's shadow, close this.

http://www.wowhead.com/spell=1090/sleep

**Comment by Nzzoth** [comment]
Thanks for the feedback, closed.

Kind regards, Nzzoth.
