### ISSUE TITLE
Gothik the Harvester

### ISSUE THREAD

**Issue by datfiyah** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5175]
Hi.
According to: http://www.wowwiki.com/Gothik_the_Harvester_%28original%29
Current situation: 5.8 million health is kinda vanilla ice, not vanilla ;p
Hotfix is most welcomed!

**Comment by Nzzoth** [comment]
Hello Datfiyah,

The developers are aware and this is going to get hotfixed, I'm closing this as there is no need for the report.

Kind regards, Nzzoth.
