### ISSUE TITLE
[Atiesh] The auras from same class don't stack.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5177]
They do stack if it's auras from different classes, but not from same class.

As they should.

**Comment by Salce** [comment]
Do you have any source ?

**Comment by Cabro** [comment]
Source no. If someone would search on internet it would be found.

I'm talking from experience.

**Comment by Salce** [comment]
I have searched far and wide on the internet to find a source for this. Your experience has proven to be wrong numerous times so I'm sorry if we can't just take that. 
If you can provide a legit source please let us know, until then we're going to deny this.

**Comment by Cabro** [comment]
This comment talks about having multiple staves to stack the buff. http://www.wowhead.com/item=22631/atiesh-greatstaff-of-the-guardian#comments:id=140516

**Comment by Kaiitothewai** [comment]
I doubt you could stack 5 Priests with 5 Priest staffs and have them all stack. Your 2nd "confirmation" part talks of 5 healers gaining 62 healing from a singular staff, you read what you want to see.

**Comment by Cabro** [comment]
I played a priest on retail. Magically, i had Atiesh. And I was also amazed when i saw that the auras stacked when me and another priest from another guild on same server tested it out. But it makes sense. It's a legendary item after all...

**Comment by Cabro** [comment]
Been wrong on some things. Mostly PvP?? 

But you doubt me in PvE, come on?!

**Comment by Rulerx** [comment]
it's also interesting to test if stacking from different classes works

**Comment by Salce** [comment]
You see there are barely any auras that stack, so it wouldn't make much sense for this one to do. As I said, I've been looking for a source but couldn't find one. If you can, feel free to post it.

**Comment by Cabro** [comment]
You are right about auras that stack with themselves. Similar aura in this regard, that doesn't stack, is the hunter's TSA.

But this is an exception, and it stacked. I gave you a source, scroll up, people were saying they stacked in 2007.

**Comment by Nzzoth** [comment]
Hello Cabro,

Please provide a source to support your issue otherwise it will get closed.

Kind regards, Nzzoth.

**Comment by Cabro** [comment]
Can you provide a source that proves they didn't stack?

Just close it, it's plain obvious you don't want to acknowledge more bugs.

**Comment by Nzzoth** [comment]
Issue closed.
