### ISSUE TITLE
[Quest] Glyph Chasing - Crystals do not give req'd quest item.

### ISSUE THREAD

**Issue by yasrynn** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5186]
Reference http://www.wowhead.com/quest=8309/glyph-chasing.

On Al'Akir, the crystals in the hives are operable but nothing happens when clicked.  You should receive a http://www.wowhead.com/item=20456/hiveregal-rubbing, http://www.wowhead.com/item=20455/hiveashi-rubbing, or http://www.wowhead.com/item=20454/hivezora-rubbing depending on which hive you are in, after operating the crystal.

As such the quest is uncompletable.

**Comment by Rulerx** [comment]
#3836

**Comment by Nzzoth** [comment]
Duplicate closed. Thanks Rulerx.
