### ISSUE TITLE
[item] Vanquished Tentacle of C'Thun

### ISSUE THREAD

**Issue by duridface** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5200]
The item (trinket) "vanquished tentacle of C'thun" does nothing when used. The line "you cast vanquished tentacle" shows up in the combat log, but the tentacle doesn't appear. 

I believe in retail, using this trinket gave you a cast circle (like flamestrike or blizzard) which allowed you to select where to place the tentacle.

**Comment by Kaiitothewai** [comment]
#3090
