### ISSUE TITLE
Totem of the Storm not properly applying damage bonuses

### ISSUE THREAD

**Issue by Sorrugis** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5218]
After testing the damage modifications of various relics I noticed that Totem of the Storm (+33 damage to Chain Lightning and Lightning Bolt) is not receiving any bonus damage.

**Comment by Kaiitothewai** [comment]
#1705 duplicate

**Comment by Sorrugis** [comment]
Had searched for a duplicate but could not find one. Sorry about that.

**Comment by Kaiitothewai** [comment]
No problem =D
