### ISSUE TITLE
[Spells]Fear teleporting rooted target

### ISSUE THREAD

**Issue by Kujiamini** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5243]
**Curent situation**
When you apply a fear effect (Fear, Psychic Scream, Intimidating Shout) to a target previously affected by a root effect (Net-o-matic, Frost Nova, Entangling Roots), this target will run - as if he fled due to fear effect - a few meters away before being root again.

*Note: If the root effect is applied after the fear effect, there is no issue, the target stays at the spot where he's been rooted.*

**How it should be like**
The target should'nt be affected by fear movement if he is rooted.

**To reproduce the bug**
*Different spells involved:*
.learn 12730 (Intimidating shout)
.learn 10891 (Psychic Scream)
.learn 6216 (Fear)
.learn 10231 (Frost Nova)
.learn 9855 (Entangling Roots)
*To use the net-o-matic root effect:*
.learn 20220
.set skill 202 300
.additem 10720

Use any of the root effect on a target, before applying any of the fear effect. You'll see the target running a few yards away instead of standing still.
For the Intimidating shout, the *target* of that spell stands still, while the targets around it actually flee. So you'll need to apply the root effect to one of those target that actually flees to test the bug.

**Comment by Kaiitothewai** [comment]
#227 duplicate
