### ISSUE TITLE
[Rogue] Blind should be a poison attack, not physical.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5251]
You can dodge/parry a Blind currently.

<code> Patch 2.3.0 (13-Nov-2007): Blind is now a physical (no longer a poison) attack. [Reagent] requirement removed. Now shares the same diminish category as Cyclone and is now diminished in PvE as well as PvP. Previously blind was a nature attack like poison. Inv misc ammo gunpowder 06 [Blinding Powder] is now a Grey-quality item ("vendor trash") which can sometimes be found in lockboxes obtained through Pickpocketing. There is a tooltip on the item that explains why Blind no longer needs a Reagent: "Once favored by rogues as a blinding agent, it was abandoned for more readily available resources... like dirt." </code>

Also check this nifty comment: http://www.wowhead.com/spell=2094/blind#comments:id=10525

**Comment by Nzzoth** [comment]
Please provide me some ingame evidence. 
Tested on PLTR with 85% dodge and 85% parry and I didn't get a single dodge or parry from blind.

**Comment by Cabro** [comment]
My bad, i confused rogue blind with http://www.wow-one.com/database/?spell=21060
Guess i'm opening a new report.
