### ISSUE TITLE
[Hunter] Mend Pet shouldn't scale with +healing.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5252]
Title.

**Comment by Kaiitothewai** [comment]
This is not true.

Rank 7 heals for 245 every tick.

You can clearly see here that it ticks for 318.
![huntervsnorth](https://cloud.githubusercontent.com/assets/2293541/7783858/955dfd58-0151-11e5-9da3-18d9e2f1e908.jpg)

And if you think the screenshot is fake, here: https://youtu.be/dXE_RR5XzE8?t=8m51s

**Comment by Cabro** [comment]
Wow you are right, this was a patch 2.1.0 change. I thought the whole "hunter soloing azuregos" was in vanilla.
