### ISSUE TITLE
[AH] You don't get messages when you successfully sold something.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5262]
You only get notifications when your auctions expire.

Recent bug.

**Comment by redmagejoe** [comment]
From what I've seen you get a mail from the auction house, but the mail is blank and gives no indication of what sold or for how much or any other details. It's more like a little red light that says "oh something sold" and you have to speculate about what it was.

I can provide a screen if needed. Blank mails should have details about the successful auction.

**Comment by Cabro** [comment]
I'm talking about the server side notification in yellow text in chat.

**Comment by Nzzoth** [comment]
Please make a seperate issue for that Redmagejoe.

**Comment by devidao** [comment]
Fixed

**Comment by killerduki** [comment]
its fixed and working on live. you can close this topic

**Comment by Kaiitothewai** [comment]
This was applied with Patch 11.7
http://www.wow-one.com/forum/topic/95872-project-phoenix-1121-changelog-patch-11/?p=730803
