### ISSUE TITLE
[Naxxramas] Plague Slime missing ability.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5264]
This mob becomes immune to a spell school when engaged. It gets a random buff from the following: 28987, 28988, 28989 and 28990.

On Feenix this mob has never taken buff id 28988 in 100+ mobs.

**Comment by Cabro** [comment]
Nvm i just stumbled upon one mob with this. Is the chance to get this aura lower than the others?

**Comment by Nzzoth** [comment]
Provide me with a source please.

**Comment by Cabro** [comment]
Source for...?

**Comment by Nzzoth** [comment]
The issue you presented while at it please try to provide sources for certain other issues you make aswell, some are obvious but others aren't.

**Comment by Cabro** [comment]
You can close this, it was incredibly bad rng with the frost debuff.

**Comment by Nzzoth** [comment]
Alright. Closed.
