### ISSUE TITLE
[Item][Alterac Valley] Insignia of the Frostwolf Rank 6 not working

### ISSUE THREAD

**Issue by stonecoast** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5267]
Insignia of the Frostwolf Rank 6 (and possibly others as well) is bugged as of a few days ago, perhaps most recent patches 14 or 14.1.  The "use" function to return to your base now always brings up an error saying "You need to be in Alterac Valley" even when in the middle of a game.

**Comment by Thetruecrow** [comment]
Wrong issue tracker, but has been resolved on TBC.

**Comment by Nzzoth** [comment]
Issue fixed and closed. This only applied to 2.4.3.
