### ISSUE TITLE
Unable to summon player with Evil Twin debuff

### ISSUE THREAD

**Issue by jeffries** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5269]
EDIT: snyffles is right.

**Comment by Snyffle** [comment]
This is working correctly.

**Comment by Cabro** [comment]
Are you sure? As far as i knew, the only side effect of Evil Twin debuff was that your character's face features were changed to more evil ones for the duration of the debuff.

Nowhere have I seen mentioned that you cannot receive a summon with the debuff active.

**Comment by Sorrugis** [comment]
I don't remember this debuff blocking summons in retail. You sure Sniff?

**Comment by Cabro** [comment]
Yea, we'd like to see PROOF of it blocking summon on retail. Else...
