### ISSUE TITLE
[Armorsmith] Last quest in chain didnt work

### ISSUE THREAD

**Issue by Chingizhan** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5272]
I finished the qst in Gadgetzan and learn to do Ornate Mithril Helm, Boots and Breastplate for last step. On wowiki i see an article:
"You can now make all the gear needed to become an Armorsmith, so return to the city and start making the 4 Ornate Mithril Helms, 2 Ornate Mithril Boots, and 1 Ornate Mithril Breastplate.
Complete the original quest by handing in your products to either Grumnus Steelshaper and you will become an Armorsmith!"
But i dont have any qst for craft this ones (( And NPC dont give me it.

Description on this chain:
http://wowwiki.wikia.com/Armorsmithing

**Comment by Cabro** [comment]
It's not THIS NPC that teaches you those. Dig more, not a bug.

**Comment by Chingizhan** [comment]
Yeah? And what about:
"Complete the original quest by handing in your products to either Official alliance Grumnus Steelshaper or Official horde mini-iconOkothos Ironrager and you will become an Armorsmith!"

Grumnus Steelshaper standing in Great Forge near anvil. And now he is inactive for me.

**Comment by Chingizhan** [comment]
Problem solved. Thanks
