### ISSUE TITLE
A pawn of the eternal board

### ISSUE THREAD

**Issue by nurman3** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5280]
The quest, "A pawn of the eternal board", does not mark itself as completed even though the quest is accepted. Also, the cutscene that (is needed for the quest) should ensue does not work/happen.
Because of this, the quest is broken and impossible to complete.

https://www.youtube.com/watch?v=VbrRwd13W7w
http://wowwiki.wikia.com/Quest%3AA_Pawn_on_the_Eternal_Board

**Comment by Kaiitothewai** [comment]
The entire quest line is already working on Emerald Dream, it's already known its not on Warsong, it will hopefully be updated at some point, no need for a GitHub issue about it again :)

**Comment by nurman3** [comment]
If only they would add it at some point....

**Comment by headlong93** [comment]
Still not working
