### ISSUE TITLE
[Quest] Nefarius Corruption

### ISSUE THREAD

**Issue by peterdimitrov** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5281]
Quests starts from Vaelastrasz the Corrupt in Blackwing Lair and instead of giving 5-hour timer as it should, it gives 2 hours.
![capture](https://cloud.githubusercontent.com/assets/13479829/8869224/0bccefbc-31ea-11e5-9f55-893f8cfbaead.PNG)

**Comment by Kaiitothewai** [comment]
The entire quest line is already working on Emerald Dream, it's already known its not on Warsong, it will hopefully be updated at some point, no need for a GitHub issue about it again :)

**Comment by peterdimitrov** [comment]
Killing Nefarian in less than 2 hours actually makes him drop the letter, not the shard. Just putting that out there in case you didn't know that. :)

**Comment by peterdimitrov** [comment]
![capture](https://cloud.githubusercontent.com/assets/13479829/12024533/a2eba3e0-adad-11e5-87fd-210c92f0d38f.PNG)
After the merge, Nefarian still drops only the letter, not the shard, although timer is still running.
