### ISSUE TITLE
[Item set] Dreamwalker Raiment 6/9 bonus

### ISSUE THREAD

**Issue by peterdimitrov** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5282]
Might be a copy of Issue #3022, which is closed for some reason.

Bonus: Your initial cast and Regrowth ticks will increase the maximum health of your target by up to 50, stacking up to 7 times.

The cast of Regrowth only ticks once and fades away from it.
On the other hand Regrowth bonus works on self or any other target that has 6 pieces of T3

**Comment by Kaiitothewai** [comment]
It's closed due to it's already reported and known on the forum, as you can see in the other report.
