### ISSUE TITLE
[Quest] Scrying Goggles? No Problem!

### ISSUE THREAD

**Issue by peterdimitrov** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5283]
Quest description:
Find Narain's Scrying Goggles and return them to Narain Soothfancy in Tanaris.

The goggles are supposed to drop from any Molten Core boss and have 5% chance of dropping from each one. After 3 full runs of Molten Core, no goggle dropped.
Therefore either I am the unluckiest person ever or the quest is bugged.

**Comment by Kaiitothewai** [comment]
The entire quest line is already working on Emerald Dream, it's already known its not on Warsong, it will hopefully be updated at some point, no need for a GitHub issue about it again :)
