### ISSUE TITLE
[Sapphiron] Al'Akir - First encounter

### ISSUE THREAD

**Issue by peterdimitrov** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5287]
1. Hitpoints of Sapphiron are way higher than they should be. At the moment they are 6,034,950.

2. The boss resets easily at the initial pull (tank charges in). Boss resets too if a raid member was offline at the initial pull and when logs back in he is at the starting point of Froswyrm Lair.

3. Ice block animation isn't done 100% of the time and if you don't have the animation, even though you have the Ice block debuff, people behind you aren't protected by it for some reason. This one is connected to Issue #5155

**Comment by Kaiitothewai** [comment]
1) Intended 
2) Your raid members are most likely standing on the snow which is causing the boss to reset (Anti Abuse)
3) This is nothing new

**Comment by peterdimitrov** [comment]
It appears to have some kind of bug with the ice gate before Kel'Thuzad. Once Sapphiron died, ice appeared to be shattering but only some people could go beyond it. We actually have to ALT-F4 through the ice... just to see the final boss :)
