### ISSUE TITLE
Words of the High Chief quest missing reward and mail delivery 

### ISSUE THREAD

**Issue by OcojFuywen** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5288]
finished a line of quests yesterday with Words of the High Chief from Donova Snowden in Winterspring... turned in Crudely-written Log to Kelek Skykeeper in Felwood... have been waiting by my mailbox for the translation and Power of the High Chief trinket..  did I miss something? no mail yet. no reward.
http://www.wow-one.com/database/index.php?quest=5128

**Comment by Kaiitothewai** [comment]
You are looking at the 2.4.3 Database

**Comment by OcojFuywen** [comment]
don't understand

**Comment by OcojFuywen** [comment]
fuck me. two versions, one website. all is clear now. so much lost time.
