### ISSUE TITLE
Feign Death broke by hotfix/patch Sept. 2015 

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5298]
http://www.wow-one.com/forum/topic/100189-latest-patchhotfix-gets-you-out-of-feign-death-after-3s-automatically/

I pinpointed the cause of the breaking effect: it's the T1/T2/T3 set bonus, pet stamina+resistance buff which somehow also breaks the cast bar.

It's sent through the STOPCAST event (name is something similar). Maybe it should be sent through other event so it doesnt trigger a stop of the bar and FD wouldn't be removed since server thinks you casted the pet buff, leading to a removal of the FD? Or make FD not removable when those pet buffs from bonuses are refreshed/applied?

Fix one, fix both? (this bug and https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/5244)

**Comment by Cabro** [comment]
Sweet this got fixed and #5244 also got fixed :)

**Comment by Nzzoth** [comment]
Closed, incase something was missed feel free to make a comment, thanks for your time.
