### ISSUE TITLE
Searing Totem

### ISSUE THREAD

**Issue by Nothhelm** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5317]
Censored.

**Comment by Yiemeh** [comment]
Rather urgent, (ab)use is widespread

**Comment by Mustybacon** [comment]
Searing Totem rank 1 benefits from spellpower at extreme levels. It's stronger than the highest rank. Pls fix so babyorc isn't strong anymore.

**Comment by Nzzoth** [comment]
Duplicate closed. #5241
