### ISSUE TITLE
[Paladin][Spell] Consecration  

### ISSUE THREAD

**Issue by illumielle** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#58]
Consecration should be scaling with attack power but it does not at the moment.

http://www.wowwiki.com/Consecration 

If you look up the patch changes in the bottom of the page you will see:

Patch 2.0.1 (05-Dec-2006): Doesn't scale with attack power anymore.

Patch 3.0.2 (14-Oct-2008): Now scales with attack power and spell power.

So i guess it used to scale with AP in Vanilla.

As a tankadin myself it is hard to gain additional aggro from consecration when it does not scale properly. I wish to enjoy the fullest of playing paladin on your server.

Thank you for your time and i hope to hear from you soon.

**Comment by Yiemeh** [comment]
Nope. This is a fake edit done few years ago in order to trick some private server into buffing paladins.

**Comment by Zerixx** [comment]
> Nope. This is a fake edit done few years ago in order to trick some private server into buffing paladins.

This is correct.

**Comment by Nzzoth** [comment]
Issue closed.
