### ISSUE TITLE
[Warlock] Minions voices broken

### ISSUE THREAD

**Issue by tecumi** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#609]
all warlock minions dont say anything when you give them orders
there is some voices scripts I could find only imp scripts
IMP
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_dismiss02.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_dismiss03.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_dismiss04.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_dismiss05.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_funny.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_kill01.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_kill02.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_kill03.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_kill04.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_order01.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_order02.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_order03.Wav")
/script PlaySoundFile("Sound\\Creature\\Impvo\\Imp_order04.Wav")

**Comment by devidao** [comment]
All sounds are
