### ISSUE TITLE
[Scholomance] Patrol that needs to be removed.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#63]
1 - There's a ghoul patrolling from the basement at Jandice Barov to the room with lots of tutors and Risen Protectors.

2 - Also there is a Risen Aberration that should also not patrol all the way upstairs from the basement.

This is 100% unblizzlike and should be removed.

**Comment by devidao** [comment]
what are they entries ?

**Comment by Cabro** [comment]
I'm sorry, I don't have access to the GM commands. I cannot possibly answer that question. Just go to Scholomance and watch what mob is patrolling. Also there is a Risen Aberration that should also not patrol all the way upstairs from the basement. 100%.
These are added by a triggerhappy dev.

**Comment by devidao** [comment]
Deleted patrol. Fix coming soon on PTR.
