### ISSUE TITLE
[Database] Elixir of Frost Power can wrongfully drop from mobs.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#64]
On database it has a 0.02% drop chance from plaguehounds. It should be a flat 0% from every possible mob. It should never drop from any mobs.
You can only acquire this during the special christmas holiday events from a quest reward container (which is actually scripted, more or less, and works).

**Comment by devidao** [comment]
Removed from loot. Fix coming soon on PTR.
