### ISSUE TITLE
[Warlock] [The Binding]

### ISSUE THREAD

**Issue by eisaar** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#67]
When summoning the voidwalker at the Stormwind Summoning Circle, the voidwalker should spawn on the Summoning Circle and attack you automatically but at the moment it won't attack you like it should it will just simply wander around without doing anything before you attack it first.

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
