### ISSUE TITLE
The Twilight Lexicon

### ISSUE THREAD

**Issue by kolomane1** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#7]
The twilight lexicon quest in silithus requires you to kill twilight keepers, problem is, one of the keepers doesnt spawn. I have camped the spawn site for 3 hours straight without seeing him spawn or his dead body.

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by anaaz** [comment]
Fix applied on live with Patch 12.1
