### ISSUE TITLE
[Hunter] Minor pet's stats bug

### ISSUE THREAD

**Issue by kokahen** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#761]
After resurrecting your pet, hes stats are not affected by talent or pet's training passives, till recalling him.

**Comment by devidao** [comment]
Can not reproduce at this moment this issue, looks working good. If issue still availalble please write reproduce guide

**Comment by Nzzoth** [comment]
**Issue tested and denied on WSG**
