### ISSUE TITLE
[Spell] [Priest] Shadowguard not working and properly

### ISSUE THREAD

**Issue by zwid** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#818]
There are two very anoying issues with the  shadowguard spell (troll priest):

One - it looks like the shaman lightning shield instead of the shadow orb it is suppose to be.

Two - it should work when shield is on, yet it does not, making it a quite useless spell for a priest.

**Comment by devidao** [comment]
* 1) spell visual is client side problem, i can not fix in on server side
* 2) Buff effect works correct

**Comment by Blaqwar** [comment]
I believe the OP is talking about Shadowguard not proccing while the Priest spell Power Word: Shield is on the target. Which might be related to the absorbed hits not activating procs issue, which might or might not have been fixed. I can't test as I don't have a troll priest.

**Comment by Nzzoth** [comment]
**Issue tested and denied**
The following issue has been resolved with a fix that effects every proc affecting targets that absorb.
As devidao stated the visual effect is a client side issue therefor this issue is closed.
