### ISSUE TITLE
[Core] Stealth and channeling.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#84]
As soon as you start channeling anything (mining/herbing/mounting/stuck/capturing bg objectives/aimed shot/auto shot/ANYTHING) your stealth should be removed.
This was working at some point, but now it's broken as fck and pvp is lame with rogues/druids stealth-capping.
Also fck NE hunters that autoshot while shadowmelded.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Forcy** [comment]
Any action besides Hearthstone can now removes any type of stealth. Fix confirmed
