### ISSUE TITLE
[Druid] Noggenfogger elixir hides druid form, giving them a tremendous pvp advantage

### ISSUE THREAD

**Issue by natx91** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#86]
The title says it all.

**Comment by Ifixstuffk** [comment]
This is blizzlike.

**Comment by natx91** [comment]
Like cross faction auction house and bugged doors is blizzlike too? This should be removed for balancing and improving PvP gameplay. You are right though, it wasn't removed till early TBC. But my point being that since feenix is no where near 100% blizzlike, they might as well fix it.

**Comment by Ifixstuffk** [comment]
Noting is balanced in pvp in vanilla, its all about the fun gimmicks.
Red bar bear
Yellow bar cat
Mana bar travel form or humanoid. You can also tell its humanoid with green casting animations.

**Comment by natx91** [comment]
Aslong as you can see the form, it's fine - hiding the form entirely is definitely not a "fun gimmick".

**Comment by Ifixstuffk** [comment]
Blizzlike as intended. 
Check the resource bar if you struggle, or get an addon.

**Comment by devidao** [comment]
How should it work? If druid is in the shapeshift form he can not get be affected "16591 Noggenfogger Elixir" spell? and at all is it a bug or not?

**Comment by sycvil** [comment]
[https://youtu.be/idTyV5HnU1c?t=8m38s](https://youtu.be/idTyV5HnU1c?t=8m38s)
At 8:38 Druid with Noggenfogger activates Travel Form and still keeps the skeleton model. Looks like not a bug.
