### ISSUE TITLE
[Database] Scholomance faction drops.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#88]
Totem of Sustaining should only drop for horde.
Libram of Divinity should only drop for alliance.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Ifixstuffk** [comment]
I distinctly recall getting paladin drops in all instances and raids as horde in retail. Is this supposed to be creature specific to scholo?

**Comment by Ifixstuffk** [comment]
Correction - this was supposed to happen only in 2.0.0 when TBC dropped, not vanilla.
