### ISSUE TITLE
Lifegiving Gem and last stand.

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#9]
Lifegiving gem and Last stand are giving twice as much hp than they should.

Reproduction:
1. Create a human warrior
2. Talent last stand
3.  .additem 19341
4. You have 2609 hp when you use last stand you'll have 4173 which is 60% more hp.

how it should be: Using last stand should increase your hp by 30% and lifegiving gem by 15%.

**Comment by anaaz** [comment]
Applied on live with Patch12
