### ISSUE TITLE
Rak'shiri attack speed

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#93]
The rare tiger Rak'shiri, when tamed, has an attack speed of 1.17.
This creature should have an attack speed of 2.00

https://dl.dropboxusercontent.com/u/22308310/Patricks%20Webpages/Hunter%20Pet%20Guide/Hunter's%20Pet%20Bestiary.html#Raptor

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
