### ISSUE TITLE
Frostsabre Pride Watcher Attack Speed

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#94]
[https://dl.dropboxusercontent.com/u/22308310/Patricks%20Webpages/Hunter%20Pet%20Guide/Hunter's%20Pet%20Bestiary.html](url)

Frostsabre Pride Watcher is supposed to have a 2.00 attack speed

All pet attack speeds may need to be reviewed. The majority of pets in the game only ever had 2.00 ASPD. Only special cases had faster than that, and I believe there was 1 slower.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
